[system]
compatible=betterframe-x86_64-generic
bootloader=grub
grubenv=/boot/efi/EFI/betterframe/grubenv
data-directory=/var/lib/rauc
bundle-formats=plain

[keyring]
path=/etc/rauc/keyring.pem

[slot.rootfs.0]
device=/dev/disk/by-partlabel/BF_ROOT_A
type=ext4
bootname=A

[slot.rootfs.1]
device=/dev/disk/by-partlabel/BF_ROOT_B
type=ext4
bootname=B
