[system]
compatible=betterframe-rpi5-aarch64
bootloader=custom
data-directory=/var/lib/rauc
bundle-formats=plain

[keyring]
path=/etc/rauc/keyring.pem

[handlers]
bootloader-custom-backend=/usr/local/sbin/betterframe-rauc-boot.sh

[slot.rootfs.0]
device=/dev/disk/by-partlabel/BF_ROOT_A
type=ext4
bootname=A

[slot.bootfs.0]
device=/dev/disk/by-partlabel/BF_BOOT_A
type=vfat
parent=rootfs.0

[slot.rootfs.1]
device=/dev/disk/by-partlabel/BF_ROOT_B
type=ext4
bootname=B

[slot.bootfs.1]
device=/dev/disk/by-partlabel/BF_BOOT_B
type=vfat
parent=rootfs.1
