//! Kiosk-side full-OS OTA via RAUC.
//!
//! Mirrors `firmware.rs` (which handles the kiosk binary) but for the
//! complete OS image. Server endpoints:
//!
//!   GET  /api/kiosk/os/check?compatibility=<X>&current=<ver>
//!     → { up_to_date: true } | { up_to_date: false, update: {...} }
//!   GET  /api/kiosk/os/download/:release_id
//!     → octet-stream .raucb bytes
//!   POST /api/kiosk/os/applied { version, error? }
//!
//! Signature verification is RAUC's job — bundles are signed with the
//! X.509 cert pair generated by scripts/gen-rauc-signing-keys.sh, and
//! the corresponding CA cert is baked into the image at
//! /etc/rauc/keyring.pem. We only sha256-check the download here to
//! catch transport corruption before handing off to `rauc install`.
//!
//! Slot switching, atomic copy, and rollback are RAUC's job too —
//! we just shell out to `rauc install`, post the outcome, and tell
//! systemd to reboot. The custom bootloader backend
//! (deploy/rauc/betterframe-rauc-boot.sh) flips Pi 5 tryboot on the
//! next boot.
//!
//! Gated by env `BF_ENABLE_OS_OTA=1`. Default OFF so dev kiosks running
//! a non-A/B layout don't try (and fail) to RAUC-install bundles.
//!
//! Compatibility: read from `/etc/betterframe/os-compatibility` (written
//! at image build time). Falls back to env `BF_RAUC_COMPATIBILITY`, then
//! a hardcoded default matching deploy/rauc/system.conf.

use std::fs;
use std::io::Read;
use std::path::PathBuf;
use std::process::{Command, Stdio};
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::Duration;

use serde::Deserialize;
use sha2::{Digest, Sha256};
use tracing::{info, warn};

pub const DEFAULT_COMPATIBILITY: &str = "betterframe-rpi5-aarch64";
static CANCEL_REQUESTED: AtomicBool = AtomicBool::new(false);

pub fn compatibility_public() -> String {
    compatibility()
}

fn compatibility() -> String {
    if let Ok(s) = fs::read_to_string("/etc/betterframe/os-compatibility") {
        let trimmed = s.trim();
        if !trimmed.is_empty() {
            return trimmed.to_string();
        }
    }
    std::env::var("BF_RAUC_COMPATIBILITY").unwrap_or_else(|_| DEFAULT_COMPATIBILITY.to_string())
}

pub fn request_cancel() {
    CANCEL_REQUESTED.store(true, Ordering::SeqCst);
    cleanup_partial_update();
}

pub fn clear_cancel() {
    CANCEL_REQUESTED.store(false, Ordering::SeqCst);
}

fn cancel_requested() -> bool {
    CANCEL_REQUESTED.load(Ordering::SeqCst)
}

fn cleanup_partial_update() {
    let staging = PathBuf::from("/var/lib/betterframe/tmp");
    let Ok(entries) = fs::read_dir(staging) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().and_then(|ext| ext.to_str()) == Some("raucb") {
            let _ = fs::remove_file(path);
        }
    }
}

pub fn current_os_version_public() -> String {
    current_os_version()
}

fn current_os_version() -> String {
    if let Ok(s) = fs::read_to_string("/etc/betterframe/os-version") {
        let trimmed = s.trim();
        if !trimmed.is_empty() {
            return trimmed.to_string();
        }
    }
    String::new()
}

#[derive(Debug, Deserialize)]
pub struct CheckResponse {
    pub up_to_date: bool,
    pub update: Option<UpdateInfo>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct UpdateInfo {
    pub release_id: String,
    pub version: String,
    #[allow(dead_code)]
    pub channel: String,
    #[allow(dead_code)]
    pub compatibility: String,
    pub sha256: String,
    pub size_bytes: u64,
    #[allow(dead_code)]
    pub bundle_format: Option<String>,
    pub download_url: String,
}

/// Hit `/api/kiosk/os/check`. Returns `Some(UpdateInfo)` when an upgrade is
/// available. `None` on up-to-date, network failure, or parse error.
pub fn check(server: &str, key: &str) -> Option<UpdateInfo> {
    let compat = compatibility();
    let cur = current_os_version();
    let url = format!(
        "{server}/api/kiosk/os/check?compatibility={compat}&current={cur}",
        compat = urlencoding::encode(&compat),
        cur = urlencoding::encode(&cur),
    );
    let client = reqwest::blocking::Client::new();
    let resp = match client
        .get(&url)
        .header("Authorization", format!("Bearer {key}"))
        .timeout(Duration::from_secs(10))
        .send()
    {
        Ok(r) => r,
        Err(err) => {
            warn!("os-update check: request failed: {err}");
            return None;
        }
    };
    if resp.status().as_u16() == 401 {
        crate::server::reset_pairing_and_restart(
            "server rejected kiosk key during os update check",
        );
    }

    if !resp.status().is_success() {
        warn!("os-update check: HTTP {}", resp.status());
        return None;
    }
    match resp.json::<CheckResponse>() {
        Ok(c) if !c.up_to_date => c.update,
        Ok(_) => None,
        Err(err) => {
            warn!("os-update check: parse failed: {err}");
            None
        }
    }
}

/// Download → sha256 verify → `rauc install` → post outcome → reboot.
///
/// On success: reboots the system (does not return). On failure: posts the
/// error to /api/kiosk/os/applied and returns Err so the caller logs it.
pub fn apply(
    server: &str,
    key: &str,
    info: &UpdateInfo,
    on_progress: impl Fn(&str, u8),
) -> Result<(), String> {
    info!(
        "os-update: applying {} ({} bytes, release {})",
        info.version, info.size_bytes, info.release_id
    );

    // 1. Download with chunked streaming + resume support.
    // Streams directly to disk (no 1.2GB in RAM). On network failure,
    // resumes from where it left off using Range header. Retries up to
    // 5 times with 10s backoff between attempts.
    let url = format!("{}{}", server, info.download_url);
    on_progress("Preparing", 0);
    let staging_dir = PathBuf::from("/var/lib/betterframe/tmp");
    fs::create_dir_all(&staging_dir).map_err(|e| format!("mkdir staging: {e}"))?;
    let bundle_path = staging_dir.join(format!("os-{}.raucb", info.release_id));

    let max_retries = 5;
    for attempt in 1..=max_retries {
        let existing_bytes = fs::metadata(&bundle_path).map(|m| m.len()).unwrap_or(0);

        // If we already have the full file from a previous attempt, skip download.
        if existing_bytes >= info.size_bytes {
            break;
        }

        info!(
            "os-update: download attempt {attempt}/{max_retries} (resuming from {existing_bytes} / {} bytes)",
            info.size_bytes
        );

        let client = reqwest::blocking::Client::new();
        let mut req = client
            .get(&url)
            .header("Authorization", format!("Bearer {key}"));
        if existing_bytes > 0 {
            req = req.header("Range", format!("bytes={existing_bytes}-"));
        }

        let resp = match req.timeout(Duration::from_secs(300)).send() {
            Ok(r) => r,
            Err(e) => {
                warn!("os-update: download request failed (attempt {attempt}): {e}");
                if attempt < max_retries {
                    std::thread::sleep(Duration::from_secs(10));
                    continue;
                }
                return Err(format!("download failed after {max_retries} attempts: {e}"));
            }
        };

        let status = resp.status().as_u16();
        if status == 401 {
            crate::server::reset_pairing_and_restart(
                "server rejected kiosk key during os update download",
            );
        }

        if status != 200 && status != 206 {
            return Err(format!("download HTTP {status}"));
        }
        let resumed = existing_bytes > 0 && status == 206;
        if existing_bytes > 0 && !resumed {
            warn!("os-update: server ignored Range; restarting download");
        }

        // Stream chunks to disk.
        use std::io::Write;
        let mut file = fs::OpenOptions::new()
            .create(true)
            .write(true)
            .append(resumed)
            .truncate(!resumed)
            .open(&bundle_path)
            .map_err(|e| format!("open bundle file: {e}"))?;

        let mut reader = resp;
        let mut buf = vec![0u8; 256 * 1024]; // 256KB chunks
        let mut downloaded = if resumed { existing_bytes } else { 0 };
        let mut stream_ok = true;

        loop {
            if cancel_requested() {
                let _ = fs::remove_file(&bundle_path);
                return Err("os update canceled after channel change".to_string());
            }
            match std::io::Read::read(&mut reader, &mut buf) {
                Ok(0) => break, // EOF
                Ok(n) => {
                    file.write_all(&buf[..n])
                        .map_err(|e| format!("write chunk: {e}"))?;
                    downloaded += n as u64;
                    let pct = ((downloaded as f64 / info.size_bytes as f64) * 90.0) as u8;
                    on_progress("Downloading", pct);
                    if downloaded % (50 * 1024 * 1024) < (256 * 1024) as u64 {
                        info!(
                            "os-update: {downloaded} / {} bytes ({pct}%)",
                            info.size_bytes
                        );
                    }
                }
                Err(e) => {
                    warn!("os-update: stream error at {downloaded} bytes (attempt {attempt}): {e}");
                    stream_ok = false;
                    break;
                }
            }
        }
        file.sync_all().ok();

        if stream_ok && downloaded >= info.size_bytes {
            break; // Download complete
        }

        if attempt < max_retries {
            info!("os-update: retrying in 10s...");
            std::thread::sleep(Duration::from_secs(10));
        } else {
            return Err(format!(
                "download incomplete after {max_retries} attempts ({downloaded}/{} bytes)",
                info.size_bytes
            ));
        }
    }

    on_progress("Verifying", 90);
    // 2. sha256 verify the complete file on disk.
    let file_size = fs::metadata(&bundle_path).map(|m| m.len()).unwrap_or(0);
    if file_size != info.size_bytes {
        let _ = fs::remove_file(&bundle_path);
        return Err(format!(
            "size mismatch: expected {}, got {file_size}",
            info.size_bytes
        ));
    }

    let mut hasher = Sha256::new();
    let mut f = fs::File::open(&bundle_path).map_err(|e| format!("open for hash: {e}"))?;
    let mut buf = vec![0u8; 256 * 1024];
    loop {
        match std::io::Read::read(&mut f, &mut buf) {
            Ok(0) => break,
            Ok(n) => hasher.update(&buf[..n]),
            Err(e) => {
                let _ = fs::remove_file(&bundle_path);
                return Err(format!("read for hash: {e}"));
            }
        }
    }
    drop(f);
    let digest = hasher.finalize();
    let got_sha = hex_lower(&digest);
    if got_sha != info.sha256 {
        let _ = fs::remove_file(&bundle_path);
        return Err(format!(
            "sha256 mismatch: expected {}, got {got_sha}",
            info.sha256
        ));
    }

    on_progress("Installing", 95);
    if cancel_requested() {
        let _ = fs::remove_file(&bundle_path);
        return Err("os update canceled after channel change".to_string());
    }
    // 4. Ensure rauc daemon is running. `rauc install` talks to the D-Bus
    // daemon; if it's not active the CLI exits with code 2.
    if let Ok(status) = Command::new("systemctl")
        .args(["is-active", "--quiet", "rauc.service"])
        .status()
    {
        if !status.success() {
            info!("os-update: rauc.service not active, attempting start");
            let start = Command::new("systemctl")
                .args(["start", "rauc.service"])
                .output();
            match start {
                Ok(out) if out.status.success() => {
                    info!("os-update: rauc.service started");
                }
                Ok(out) => {
                    let stderr = String::from_utf8_lossy(&out.stderr);
                    let msg = format!("rauc.service failed to start: {stderr}");
                    warn!("os-update: {msg}");
                    let _ = report_applied(server, key, &info.version, Some(&msg));
                    let _ = fs::remove_file(&bundle_path);
                    return Err(msg);
                }
                Err(e) => {
                    let msg = format!("systemctl start rauc.service: {e}");
                    warn!("os-update: {msg}");
                    let _ = report_applied(server, key, &info.version, Some(&msg));
                    let _ = fs::remove_file(&bundle_path);
                    return Err(msg);
                }
            }
        }
    }

    // Hand off to rauc. `rauc install` blocks until the bundle is fully
    // copied into the inactive slot and bootloader is flipped. Exit code 0
    // = success; anything else = leave current slot booted, no reboot.
    let mut child = Command::new("rauc")
        .args(["install", bundle_path.to_str().unwrap_or("")])
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| {
            let _ = report_applied(
                server,
                key,
                &info.version,
                Some(&format!("rauc spawn: {e}")),
            );
            format!("rauc spawn: {e}")
        })?;
    let mut child_stdout = child
        .stdout
        .take()
        .ok_or_else(|| "rauc stdout missing".to_string())?;
    let mut child_stderr = child
        .stderr
        .take()
        .ok_or_else(|| "rauc stderr missing".to_string())?;
    let stdout_reader = std::thread::spawn(move || {
        let mut bytes = Vec::new();
        let _ = child_stdout.read_to_end(&mut bytes);
        bytes
    });
    let stderr_reader = std::thread::spawn(move || {
        let mut bytes = Vec::new();
        let _ = child_stderr.read_to_end(&mut bytes);
        bytes
    });
    let status = loop {
        if cancel_requested() {
            let _ = child.kill();
            let _ = child.wait();
            let _ = report_applied(
                server,
                key,
                &info.version,
                Some("os update canceled after channel change"),
            );
            let _ = fs::remove_file(&bundle_path);
            return Err("os update canceled after channel change".to_string());
        }
        match child.try_wait() {
            Ok(Some(status)) => break status,
            Ok(None) => std::thread::sleep(Duration::from_secs(1)),
            Err(e) => {
                let _ = fs::remove_file(&bundle_path);
                return Err(format!("rauc wait: {e}"));
            }
        }
    };
    let stdout = stdout_reader.join().unwrap_or_default();
    let stderr = stderr_reader.join().unwrap_or_default();
    if !status.success() {
        let msg = format_command_failure("rauc install", status, &stdout, &stderr);
        warn!("os-update: {msg}");
        let _ = report_applied(server, key, &info.version, Some(&msg));
        let _ = fs::remove_file(&bundle_path);
        return Err(msg);
    }
    let _ = fs::remove_file(&bundle_path);

    // 5. Report success BEFORE reboot. After this we lose the server
    // connection mid-call; that's fine, server sets last_attempt_at from
    // the next heartbeat anyway, but recording success now means the
    // admin UI shows progress immediately.
    let _ = report_applied(server, key, &info.version, None);
    crate::update_guard::record_success("os", &info.version);

    on_progress("Rebooting", 100);
    info!("os-update: rauc install OK → rebooting into the new slot");
    // RAUC's custom bootloader backend has already armed tryboot for the
    // freshly-written slot. Reboot picks it up. On failure to reach the
    // new slot, tryboot rolls back automatically on the next power cycle.
    let mut reboot = if compatibility().contains("rpi") {
        let mut command = Command::new("sudo");
        command.args(["-n", "/usr/sbin/reboot", "0", "tryboot"]);
        command
    } else {
        let mut command = Command::new("sudo");
        command.args(["-n", "/usr/bin/systemctl", "reboot"]);
        command
    };
    match reboot.status() {
        Ok(status) if status.success() => {
            // systemctl reboot returns before the reboot completes; sleep
            // briefly so we don't race main() into a re-entry.
            std::thread::sleep(Duration::from_secs(30));
            std::process::exit(0);
        }
        Ok(status) => {
            let message = format!("privileged reboot failed: {status}");
            let _ = report_applied(server, key, &info.version, Some(&message));
            Err(message)
        }
        Err(e) => {
            let message = format!("privileged reboot: {e}");
            let _ = report_applied(server, key, &info.version, Some(&message));
            Err(message)
        }
    }
}

fn report_applied(
    server: &str,
    key: &str,
    version: &str,
    error: Option<&str>,
) -> Result<(), String> {
    let payload = if let Some(err) = error {
        serde_json::json!({ "version": version, "state": "failed", "error": err })
    } else {
        serde_json::json!({ "version": version, "state": "pending_reboot" })
    };
    reqwest::blocking::Client::new()
        .post(format!("{server}/api/kiosk/os/status"))
        .header("Authorization", format!("Bearer {key}"))
        .json(&payload)
        .timeout(Duration::from_secs(5))
        .send()
        .map(|_| ())
        .map_err(|e| format!("report applied: {e}"))
}

pub fn report_confirmed(server: &str, key: &str) -> bool {
    let version =
        fs::read_to_string("/etc/betterframe/os-version").unwrap_or_else(|_| "unknown".to_string());
    reqwest::blocking::Client::new()
        .post(format!("{server}/api/kiosk/os/status"))
        .header("Authorization", format!("Bearer {key}"))
        .json(&serde_json::json!({ "version": version.trim(), "state": "confirmed" }))
        .timeout(Duration::from_secs(5))
        .send()
        .map(|response| response.status().is_success())
        .unwrap_or(false)
}

pub fn boot_is_confirmed() -> bool {
    std::path::Path::new("/run/betterframe/rauc-confirmed").exists()
        || !std::path::Path::new("/etc/rauc/system.conf").exists()
}

fn format_command_failure(
    command: &str,
    status: std::process::ExitStatus,
    stdout: &[u8],
    stderr: &[u8],
) -> String {
    let code = status
        .code()
        .map(|c| c.to_string())
        .unwrap_or_else(|| "unknown".to_string());
    let mut msg = format!("{command} failed (exit code {code}, status {status:?})");
    append_command_output(&mut msg, "stdout", stdout);
    append_command_output(&mut msg, "stderr", stderr);
    msg
}

fn append_command_output(msg: &mut String, label: &str, bytes: &[u8]) {
    let text = String::from_utf8_lossy(bytes);
    let trimmed = text.trim();
    if trimmed.is_empty() {
        return;
    }

    const MAX_OUTPUT_CHARS: usize = 4000;
    msg.push_str("; ");
    msg.push_str(label);
    msg.push_str(": ");
    if trimmed.chars().count() <= MAX_OUTPUT_CHARS {
        msg.push_str(trimmed);
        return;
    }

    let start = trimmed
        .char_indices()
        .nth(trimmed.chars().count().saturating_sub(MAX_OUTPUT_CHARS))
        .map(|(idx, _)| idx)
        .unwrap_or(0);
    msg.push_str("[truncated] ");
    msg.push_str(&trimmed[start..]);
}

fn hex_lower(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push(HEX[(b >> 4) as usize] as char);
        s.push(HEX[(b & 0x0f) as usize] as char);
    }
    s
}
