d /run/betterframe 0755 bfkiosk bfkiosk -
d /var/lib/betterframe/kiosk 0755 bfkiosk bfkiosk -
d /var/lib/betterframe/tmp 0755 bfkiosk bfkiosk -
d /var/lib/betterframe/recordings 0750 bfkiosk bfkiosk -
