const FAV_KEY="betterframe.operator.favorites";
const RECENT_KEY="betterframe.operator.recent";
const WALL_KEY="betterframe.operator.wallTarget";
const state={bootstrap:null,camera:null,selectedCameraIds:new Set(),stream:"main",filter:"all",duration:60,pc:null,whepResource:null,previewGeneration:0,previewAbort:null,hid:null,hidTimer:null};
const $=id=>document.getElementById(id);
const jsonStore={get:(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}},set:(key,value)=>localStorage.setItem(key,JSON.stringify(value))};
async function api(path,options={}){const headers=new Headers(options.headers||{});if(options.body&&!headers.has("content-type"))headers.set("content-type","application/json");const response=await fetch(path,{...options,headers});if(response.status===401)throw new Error("unauthorized");if(!response.ok){let text=await response.text();throw new Error(text||`Request failed (${response.status})`)}const type=response.headers.get("content-type")||"";return type.includes("json")?response.json():response}
async function boot(){try{state.bootstrap=await api("/operator/api/bootstrap");$("enroll").classList.add("hidden");$("console").classList.remove("hidden");render();reconnectGrantedHid()}catch(err){if(err.message==="unauthorized"){$("console").classList.add("hidden");$("enroll").classList.remove("hidden")}else{$("enroll-error").textContent=err.message;$("enroll").classList.remove("hidden")}}}
$("enroll-form").addEventListener("submit",async event=>{event.preventDefault();$("enroll-error").textContent="";try{await api("/operator/api/enroll",{method:"POST",body:JSON.stringify({code:$("enroll-code").value})});await boot()}catch(err){$("enroll-error").textContent=err.message}});
function visibleCameras(){const q=$("search").value.trim().toLowerCase();const favorites=jsonStore.get(FAV_KEY,[]);const recent=jsonStore.get(RECENT_KEY,[]);let cameras=[...(state.bootstrap?.cameras||[])];if(state.filter==="favorites")cameras=cameras.filter(camera=>favorites.includes(camera.id));if(state.filter==="recent")cameras.sort((a,b)=>recent.indexOf(a.id)-recent.indexOf(b.id)).filter(camera=>recent.includes(camera.id));if(q)cameras=cameras.filter(camera=>[camera.name,camera.camera_number,camera.device_name,...camera.labels].filter(Boolean).join(" ").toLowerCase().includes(q));return cameras}
function render(){renderCameras();renderWalls();if(!state.camera&&state.bootstrap.cameras.length)selectCamera(state.bootstrap.cameras[0].id)}
function cameraGroups(cameras){const groups=new Map();for(const camera of cameras){const id=camera.device_id||"standalone";if(!groups.has(id))groups.set(id,{id,name:camera.device_name||"Standalone cameras",cameras:[]});groups.get(id).cameras.push(camera)}return [...groups.values()].sort((a,b)=>a.name.localeCompare(b.name))}
function updateSelectionCount(){const count=state.selectedCameraIds.size;$("selection-count").textContent=`${count} selected`;$("clear-selection").disabled=count===0}
function setCameraSelected(id,selected){if(selected)state.selectedCameraIds.add(id);else state.selectedCameraIds.delete(id);renderCameras()}
function renderCameras(){const list=$("camera-list");const cameras=visibleCameras();updateSelectionCount();if(!cameras.length){const empty=document.createElement("p");empty.className="muted empty-state";empty.textContent=state.bootstrap?.cameras.length?"No cameras match this filter.":"No cameras are assigned to this kiosk with an operate label.";list.replaceChildren(empty);return}const favorites=jsonStore.get(FAV_KEY,[]);list.replaceChildren(...cameraGroups(cameras).map(group=>{const section=document.createElement("section");section.className="camera-group";const header=document.createElement("label");header.className="camera-group-title";const groupPick=document.createElement("input");groupPick.type="checkbox";const selectedCount=group.cameras.filter(camera=>state.selectedCameraIds.has(camera.id)).length;groupPick.checked=selectedCount===group.cameras.length;groupPick.indeterminate=selectedCount>0&&!groupPick.checked;groupPick.onchange=()=>{for(const camera of group.cameras){if(groupPick.checked)state.selectedCameraIds.add(camera.id);else state.selectedCameraIds.delete(camera.id)}renderCameras()};const title=document.createElement("span");title.textContent=group.name;const count=document.createElement("small");count.textContent=String(group.cameras.length);header.append(groupPick,title,count);section.append(header);for(const camera of group.cameras){const row=document.createElement("div");row.className=`camera-row${state.camera?.id===camera.id?" selected":""}`;const pick=document.createElement("input");pick.type="checkbox";pick.checked=state.selectedCameraIds.has(camera.id);pick.setAttribute("aria-label",`Select ${camera.name}`);pick.onchange=()=>setCameraSelected(camera.id,pick.checked);const status=document.createElement("i");status.className=`status ${camera.status}`;const open=document.createElement("button");open.type="button";open.className="camera-open";open.innerHTML='<span class="camera-title"></span><span class="camera-sub"></span>';open.querySelector(".camera-title").textContent=camera.camera_number?`${camera.camera_number} · ${camera.name}`:camera.name;open.querySelector(".camera-sub").textContent=camera.labels.join(" · ")||camera.status;open.onclick=()=>selectCamera(camera.id);const favorite=document.createElement("span");favorite.textContent=favorites.includes(camera.id)?"★":"";row.append(pick,status,open,favorite);section.append(row)}return section}))}
function selectCamera(id){const camera=state.bootstrap.cameras.find(item=>item.id===id);if(!camera)return;state.camera=camera;const recent=jsonStore.get(RECENT_KEY,[]).filter(item=>item!==id);recent.unshift(id);jsonStore.set(RECENT_KEY,recent.slice(0,20));const streams=new Set(camera.streams.map(item=>item.role));if(!streams.has(state.stream))state.stream=streams.has("main")?"main":camera.streams[0]?.role||"main";$("camera-name").textContent=camera.name;$("camera-meta").textContent=[camera.device_name,camera.camera_number,...camera.labels,camera.status].filter(Boolean).join(" · ");const favorites=jsonStore.get(FAV_KEY,[]);$("favorite").textContent=favorites.includes(id)?"★":"☆";document.querySelectorAll("[data-stream]").forEach(button=>{button.disabled=!streams.has(button.dataset.stream);button.classList.toggle("active",button.dataset.stream===state.stream)});const hasPtz=camera.capabilities.some(item=>item.toLowerCase()==="ptz");$("ptz-controls").classList.toggle("hidden",!hasPtz);$("controls-grid").style.gridTemplateColumns=hasPtz?"":"1fr";renderCameras();renderPresets();preview()}
async function preview(){const generation=++state.previewGeneration;state.previewAbort?.abort();const abort=new AbortController();state.previewAbort=abort;const oldResource=state.whepResource;state.whepResource=null;state.pc?.close();state.pc=null;$("video").srcObject=null;if(oldResource)api(oldResource,{method:"DELETE"}).catch(()=>{});if(!state.camera)return;const cameraId=state.camera.id,stream=state.stream;$("video-state").textContent="Connecting…";$("video-state").style.display="grid";let pc=null,resource=null;try{const session=await api("/operator/api/media/session",{method:"POST",body:JSON.stringify({camera_id:cameraId,stream}),signal:abort.signal});if(generation!==state.previewGeneration)return;pc=new RTCPeerConnection();state.pc=pc;pc.addTransceiver("video",{direction:"recvonly"});pc.ontrack=event=>{if(generation!==state.previewGeneration)return;$("video").srcObject=event.streams[0]||new MediaStream([event.track]);$("video-state").style.display="none"};pc.onconnectionstatechange=()=>{if(generation===state.previewGeneration&&["failed","disconnected"].includes(pc.connectionState)){$("video-state").textContent="Live view disconnected";$("video-state").style.display="grid"}};const offer=await pc.createOffer();await pc.setLocalDescription(offer);await waitForIce(pc);if(generation!==state.previewGeneration){pc.close();return}const response=await api(session.whep_url,{method:"POST",headers:{"content-type":"application/sdp"},body:pc.localDescription.sdp,signal:abort.signal});resource=response.headers.get("location");if(generation!==state.previewGeneration){pc.close();if(resource)api(resource,{method:"DELETE"}).catch(()=>{});return}state.whepResource=resource;const sdp=await response.text();if(generation!==state.previewGeneration){pc.close();return}await pc.setRemoteDescription({type:"answer",sdp})}catch(err){pc?.close();if(generation!==state.previewGeneration||err.name==="AbortError")return;state.pc=null;state.whepResource=null;if(resource)api(resource,{method:"DELETE"}).catch(()=>{});$("video-state").textContent=err.message.includes("codec")?"Unsupported browser codec — try Sub stream":err.message;$("video-state").style.display="grid"}}
function waitForIce(pc){if(pc.iceGatheringState==="complete")return Promise.resolve();return new Promise(resolve=>{const timeout=setTimeout(resolve,3000);pc.addEventListener("icegatheringstatechange",()=>{if(pc.iceGatheringState==="complete"){clearTimeout(timeout);resolve()}},{once:false})})}
async function stopPreview(){++state.previewGeneration;state.previewAbort?.abort();state.previewAbort=null;const resource=state.whepResource;state.whepResource=null;state.pc?.close();state.pc=null;$("video").srcObject=null;if(resource)try{await api(resource,{method:"DELETE"})}catch{}}
document.querySelectorAll("[data-stream]").forEach(button=>button.onclick=()=>{state.stream=button.dataset.stream;document.querySelectorAll("[data-stream]").forEach(item=>item.classList.toggle("active",item===button));preview()});
document.querySelectorAll("[data-filter]").forEach(button=>button.onclick=()=>{state.filter=button.dataset.filter;document.querySelectorAll("[data-filter]").forEach(item=>item.classList.toggle("active",item===button));renderCameras()});
$("search").addEventListener("input",renderCameras);$("select-visible").onclick=()=>{for(const camera of visibleCameras())state.selectedCameraIds.add(camera.id);renderCameras()};$("clear-selection").onclick=()=>{state.selectedCameraIds.clear();renderCameras()};$("favorite").onclick=()=>{if(!state.camera)return;let items=jsonStore.get(FAV_KEY,[]);items=items.includes(state.camera.id)?items.filter(id=>id!==state.camera.id):[...items,state.camera.id];jsonStore.set(FAV_KEY,items);renderCameras();$("favorite").textContent=items.includes(state.camera.id)?"★":"☆"};
function stepCamera(delta){const list=visibleCameras();const index=Math.max(0,list.findIndex(camera=>camera.id===state.camera?.id));if(list.length)selectCamera(list[(index+delta+list.length)%list.length].id)}$("previous").onclick=()=>stepCamera(-1);$("next").onclick=()=>stepCamera(1);
async function onvif(action,params={}){if(!state.camera)throw new Error("Select a camera");const profileToken=state.camera.streams.find(item=>item.role===state.stream)?.profile_token||state.camera.streams[0]?.profile_token;return api(`/operator/api/cameras/${encodeURIComponent(state.camera.id)}/onvif`,{method:"POST",body:JSON.stringify({action,params:{...params,profileToken}})})}
let ptzActive=false;async function ptzMove(pan,tilt,zoom){ptzActive=true;try{await onvif("ptz.continuous_move",{pan,tilt,zoom,timeoutMs:500})}catch{}}async function ptzStop(){if(!ptzActive)return;ptzActive=false;try{await onvif("ptz.stop",{panTilt:true,zoom:true})}catch{}}
document.querySelectorAll("[data-ptz]").forEach(button=>{const values=button.dataset.ptz.split(",").map(Number);button.addEventListener("pointerdown",()=>ptzMove(...values));button.addEventListener("pointerup",ptzStop);button.addEventListener("pointercancel",ptzStop);button.addEventListener("pointerleave",ptzStop)});document.querySelector("[data-ptz-stop]").onclick=ptzStop;window.addEventListener("blur",ptzStop);
async function renderPresets(){const select=$("preset");select.innerHTML='<option value="">Preset…</option>';if(!state.camera?.capabilities.some(item=>item.toLowerCase()==="ptz"))return;try{const result=await onvif("ptz.get_presets");for(const preset of result.result?.data?.presets||[]){const option=document.createElement("option");option.value=preset.token;option.textContent=preset.name||preset.token;select.append(option)}}catch{}}$("preset").onchange=()=>{$("preset").value&&onvif("ptz.goto_preset",{presetToken:$("preset").value})};
function renderWalls(){const selected=jsonStore.get(WALL_KEY,{});const display=state.bootstrap.displays.find(item=>item.id===selected.display_id)||state.bootstrap.displays[0];const container=$("wall-buttons");container.replaceChildren(...state.bootstrap.displays.map((item,index)=>{const button=document.createElement("button");button.textContent=item.name||`Wall ${index+1}`;button.classList.toggle("active",item.id===display?.id);button.onclick=()=>{jsonStore.set(WALL_KEY,{display_id:item.id,cell_id:null});renderWalls()};return button}));const cell=$("wall-cell");cell.innerHTML='<option value="">First empty tile (never overwrite)</option>';for(const [index,item] of (display?.cells||[]).entries()){const option=document.createElement("option");option.value=item.id;const content=item.camera_name||(item.content_type!=="none"?item.content_type:"Empty");option.textContent=`Tile ${index+1} — ${content}`;option.selected=selected.cell_id===item.id;cell.append(option)}cell.onchange=()=>jsonStore.set(WALL_KEY,{display_id:display?.id,cell_id:cell.value||null})}
document.querySelectorAll("[data-duration]").forEach(button=>button.onclick=()=>{state.duration=button.dataset.duration==="pin"?null:Number(button.dataset.duration);document.querySelectorAll("[data-duration]").forEach(item=>item.classList.toggle("active",item===button))});
function selectedDisplayId(){const selected=jsonStore.get(WALL_KEY,{});return selected.display_id||state.bootstrap.displays[0]?.id}
function selectedCameras(){const cameras=state.bootstrap.cameras.filter(camera=>state.selectedCameraIds.has(camera.id));return cameras.length?cameras:(state.camera?[state.camera]:[])}
function streamFor(camera){return camera.streams.some(stream=>stream.role===state.stream)?state.stream:(camera.streams.some(stream=>stream.role==="main")?"main":"sub")}
async function focus(camera,displayId,fullscreen,cellId=null){return api(`/operator/api/displays/${encodeURIComponent(displayId)}/focus`,{method:"POST",body:JSON.stringify({camera_id:camera.id,stream:streamFor(camera),target:fullscreen?{kind:"fullscreen"}:{kind:"cell",cell_id:cellId},duration_seconds:state.duration,restore:"previous"})})}
function setWallBusy(busy){for(const id of ["wall-send","wall-span","wall-fullscreen","wall-clear","wall-restore"])$(id).disabled=busy}
async function wallAction(action){setWallBusy(true);try{await action()}catch(err){$("wall-state").textContent=err.message}finally{setWallBusy(false)}}
$("wall-send").onclick=()=>wallAction(async()=>{const displayId=selectedDisplayId();const cameras=selectedCameras();if(!displayId)throw new Error("No display is available");if(!cameras.length)throw new Error("Select a camera");let cellId=$("wall-cell").value||null;for(const camera of cameras){await focus(camera,displayId,false,cellId);cellId=null}$("wall-state").textContent=`Sent ${cameras.length} camera${cameras.length===1?"":"s"} to the selected display`});
$("wall-span").onclick=()=>wallAction(async()=>{const cameras=selectedCameras();const displays=state.bootstrap.displays;if(!cameras.length)throw new Error("Select cameras to distribute");if(!displays.length)throw new Error("No display is available");let cursor=Math.max(0,displays.findIndex(display=>display.id===selectedDisplayId()));for(const camera of cameras){let placed=false;for(let attempt=0;attempt<displays.length;attempt++){const index=(cursor+attempt)%displays.length;try{await focus(camera,displays[index].id,false,null);cursor=(index+1)%displays.length;placed=true;break}catch(err){if(!err.message.includes("no empty target tile"))throw err}}if(!placed)throw new Error("No empty tiles remain across displays")}$("wall-state").textContent=`Distributed ${cameras.length} camera${cameras.length===1?"":"s"} across displays`});
$("wall-fullscreen").onclick=()=>wallAction(async()=>{const displayId=selectedDisplayId();if(!displayId)throw new Error("No display is available");if(!state.camera)throw new Error("Select a preview camera");await focus(state.camera,displayId,true);$("wall-state").textContent=`Focused ${state.camera.name} full-screen`});$("wall-restore").onclick=()=>wallAction(async()=>{const displayId=selectedDisplayId();if(displayId)await api(`/operator/api/displays/${encodeURIComponent(displayId)}/overrides`,{method:"DELETE"});$("wall-state").textContent="Previous layout restored"});$("wall-clear").onclick=()=>wallAction(async()=>{const displayId=selectedDisplayId();if(displayId)await api(`/operator/api/displays/${encodeURIComponent(displayId)}/clear`,{method:"POST",body:"{}"});$("wall-state").textContent="Display cleared; Restore layout to return"});
async function reconnectGrantedHid(){if(!navigator.hid)return;const devices=await navigator.hid.getDevices();if(devices[0])attachHid(devices[0])}$("connect-hid").onclick=async()=>{if(!navigator.hid){$("hid-state").textContent="WebHID is unavailable in this browser";return}try{const devices=await navigator.hid.requestDevice({filters:[]});if(devices[0])attachHid(devices[0])}catch(err){$("hid-state").textContent=err.message}};
async function attachHid(device){if(!device.opened)await device.open();state.hid=device;$("hid-state").textContent=device.productName||"HID joystick connected";device.addEventListener("inputreport",event=>{const data=new Uint8Array(event.data.buffer);if(data.length<3)return;const axis=value=>(value-128)/127;const pan=Math.abs(axis(data[0]))>.15?axis(data[0]):0;const tilt=Math.abs(axis(data[1]))>.15?-axis(data[1]):0;const zoom=Math.abs(axis(data[2]))>.15?axis(data[2]):0;if(pan||tilt||zoom)ptzMove(pan,tilt,zoom);else ptzStop();clearTimeout(state.hidTimer);state.hidTimer=setTimeout(ptzStop,250)})}
window.addEventListener("beforeunload",()=>{ptzStop();stopPreview()});boot();
