//! Kiosk-side full-OS OTA via RAUC.
//!
//! Mirrors `firmware.rs` (which handles the kiosk binary) but for the
//! complete OS image. Server endpoints:
//!
//!   GET  /api/kiosk/os/check?compatibility=<X>&current=<ver>
//!     → { up_to_date: true } | { up_to_date: false, update: {...} }
//!   GET  /api/kiosk/os/download/:release_id
//!     → octet-stream .raucb bytes
//!   POST /api/kiosk/os/applied { version, error? }
//!
//! Signature verification is RAUC's job — bundles are signed with the
//! X.509 cert pair generated by scripts/gen-rauc-signing-keys.sh, and
//! the corresponding CA cert is baked into the image at
//! /etc/rauc/keyring.pem. We only sha256-check the download here to
//! catch transport corruption before handing off to `rauc install`.
//!
//! Slot switching, atomic copy, and rollback are RAUC's job too —
//! we just shell out to `rauc install`, post the outcome, and tell
//! systemd to reboot. The custom bootloader backend
//! (deploy/rauc/betterframe-rauc-boot.sh) flips Pi 5 tryboot on the
//! next boot.
//!
//! Enabled only on full BetterFrame OS images with RAUC configuration and
//! image identity files. `BF_ENABLE_OS_OTA=0` additionally disables OS updates.
//!
//! Compatibility: read from `/etc/betterframe/os-compatibility` (written
//! at image build time). Falls back to env `BF_RAUC_COMPATIBILITY`, then
//! a hardcoded default matching deploy/rauc/system.conf.

#[path = "os_installation.rs"]
mod os_installation;

pub fn enabled() -> bool {
    os_installation::updates_enabled(
        std::path::Path::new("/"),
        std::env::var("BF_ENABLE_OS_OTA").ok().as_deref(),
    )
}

use crate::os_journal::{self, Journal, Stage};
use std::fs;
use std::sync::Mutex;
const JOURNAL_PATH: &str = "/var/lib/betterframe/kiosk/os-update.json";
static JOURNAL_LOCK: Mutex<()> = Mutex::new(());
fn boot_id() -> String {
    fs::read_to_string("/proc/sys/kernel/random/boot_id")
        .unwrap_or_default()
        .trim()
        .to_string()
}

pub fn last_update_note() -> Option<String> {
    let _lock = JOURNAL_LOCK.lock().ok()?;
    match os_journal::read(std::path::Path::new(JOURNAL_PATH)) {
        Ok(Some(j)) => j.error.clone().or_else(|| {
            if j.blocks_apply() {
                Some(format!(
                    "OS update {} awaits boot confirmation. Manage updates in BetterFrame.",
                    j.version
                ))
            } else {
                None
            }
        }),
        Err(e) => Some(e),
        _ => None,
    }
}

fn save_stage(stage: Stage, error: Option<String>) -> Result<(), String> {
    let _lock = JOURNAL_LOCK.lock().map_err(|_| "OS update record locked")?;
    let path = std::path::Path::new(JOURNAL_PATH);
    if let Some(mut j) = os_journal::read(path)? {
        j.stage = stage;
        j.error = error;
        os_journal::write(path, &j)?;
    }
    Ok(())
}

use std::io::Read;
use std::path::PathBuf;
use std::process::{Command, Stdio};
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::Duration;

use serde::Deserialize;
use sha2::{Digest, Sha256};
use tracing::{info, warn};

pub const DEFAULT_COMPATIBILITY: &str = "betterframe-rpi5-aarch64";
static CANCEL_REQUESTED: AtomicBool = AtomicBool::new(false);
fn installer_idle() -> bool {
    Command::new("busctl")
        .args([
            "get-property",
            "de.pengutronix.rauc",
            "/",
            "de.pengutronix.rauc.Installer",
            "Operation",
        ])
        .output()
        .map(|o| o.status.success() && String::from_utf8_lossy(&o.stdout).trim() == "s \"idle\"")
        .unwrap_or(false)
}

pub fn compatibility_public() -> String {
    compatibility()
}

fn compatibility() -> String {
    if let Ok(s) = fs::read_to_string("/etc/betterframe/os-compatibility") {
        let trimmed = s.trim();
        if !trimmed.is_empty() {
            return trimmed.to_string();
        }
    }
    std::env::var("BF_RAUC_COMPATIBILITY").unwrap_or_else(|_| DEFAULT_COMPATIBILITY.to_string())
}

pub fn request_cancel() {
    // Only the active downloader may discard its file. A channel change must
    // never unlink a bundle that the root RAUC daemon might still be using.
    CANCEL_REQUESTED.store(true, Ordering::SeqCst);
}

pub fn clear_cancel() {
    CANCEL_REQUESTED.store(false, Ordering::SeqCst);
}

fn cancel_requested() -> bool {
    CANCEL_REQUESTED.load(Ordering::SeqCst)
}

pub fn current_os_version_public() -> String {
    current_os_version()
}

fn current_os_version() -> String {
    if let Ok(s) = fs::read_to_string("/etc/betterframe/os-version") {
        let trimmed = s.trim();
        if !trimmed.is_empty() {
            return trimmed.to_string();
        }
    }
    String::new()
}

#[derive(Debug, Deserialize)]
pub struct CheckResponse {
    pub up_to_date: bool,
    pub update: Option<UpdateInfo>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct UpdateInfo {
    pub release_id: String,
    pub version: String,
    #[allow(dead_code)]
    pub channel: String,
    #[allow(dead_code)]
    pub compatibility: String,
    pub sha256: String,
    pub size_bytes: u64,
    #[allow(dead_code)]
    pub bundle_format: Option<String>,
    pub download_url: String,
}

/// Public stable-channel check used before the kiosk has paired.
pub fn check_public(server: &str) -> Option<UpdateInfo> {
    check_at(server, None, "/api/os/public/check")
}

/// Authenticated check used after pairing.
pub fn check(server: &str, key: &str) -> Option<UpdateInfo> {
    check_at(server, Some(key), "/api/kiosk/os/check")
}

fn check_at(server: &str, key: Option<&str>, path: &str) -> Option<UpdateInfo> {
    if !enabled() {
        return None;
    }
    let compat = compatibility();
    let cur = current_os_version();
    let url = format!(
        "{server}{path}?compatibility={compat}&current={cur}",
        compat = urlencoding::encode(&compat),
        cur = urlencoding::encode(&cur),
    );
    let client = crate::network::blocking_client();
    let mut request = client.get(&url);
    if let Some(key) = key {
        request = request.header("Authorization", format!("Bearer {key}"));
    }
    let resp = match request.timeout(Duration::from_secs(10)).send() {
        Ok(r) => r,
        Err(err) => {
            warn!("os-update check: request failed: {err}");
            return None;
        }
    };

    if !resp.status().is_success() {
        warn!("os-update check: HTTP {}", resp.status());
        return None;
    }
    match resp.json::<CheckResponse>() {
        Ok(c) => newer_update(c, &cur),
        Err(err) => {
            warn!("os-update check: parse failed: {err}");
            None
        }
    }
}

/// Download → sha256 verify → `rauc install` → post outcome → reboot.
///
/// On success: reboots the system (does not return). On failure: posts the
/// error to /api/kiosk/os/applied and returns Err so the caller logs it.
pub fn apply(
    server: &str,
    key: &str,
    info: &UpdateInfo,
    on_progress: impl Fn(&str, u8),
    force: bool,
) -> Result<(), String> {
    apply_tracked(server, Some(key), info, on_progress, force)
}

pub fn apply_public(
    server: &str,
    info: &UpdateInfo,
    on_progress: impl Fn(&str, u8),
) -> Result<(), String> {
    apply_tracked(server, None, info, on_progress, false)
}

fn apply_tracked(
    server: &str,
    key: Option<&str>,
    info: &UpdateInfo,
    on_progress: impl Fn(&str, u8),
    force: bool,
) -> Result<(), String> {
    if !enabled() {
        return Err("OS updates require a full BetterFrame OS installation".into());
    }
    ensure_upgrade(info, &current_os_version())?;
    let id = boot_id();
    if id.is_empty() {
        return Err("Cannot identify this boot; OS update deferred".into());
    }
    {
        let _lock = JOURNAL_LOCK.lock().map_err(|_| "OS update record locked")?;
        let path = std::path::Path::new(JOURNAL_PATH);
        if let Some(mut j) = os_journal::read(path)? {
            j.reconcile(&id, &current_os_version(), boot_is_confirmed());
            os_journal::write(path, &j)?;
            if j.blocks_apply() && force && !installer_idle() {
                return Err(
                    "OS installer is still busy or unavailable; retry after installation finishes"
                        .into(),
                );
            }
            if j.blocks_apply() && !force {
                return Err(j.error.unwrap_or_else(|| format!("OS update {} is awaiting reboot/confirmation; retry from BetterFrame if needed", j.version)));
            }
        }
        if let Some(n) = crate::update_guard::blocked("os", &info.version, force) {
            return Err(format!(
                "OS update {} paused after {n} attempts. Pair this display and retry from BetterFrame.",
                info.version
            ));
        }
        os_journal::write(
            path,
            &Journal {
                version: info.version.clone(),
                release_id: info.release_id.clone(),
                boot_id: id,
                stage: Stage::Downloading,
                error: None,
            },
        )?;
        // Count before starting so power loss also consumes an attempt.
        crate::update_guard::record_attempt("os", &info.version)?;
    }
    let result = apply_inner(server, key, info, on_progress);
    if let Err(ref error) = result {
        let _lock = JOURNAL_LOCK.lock().map_err(|_| "OS update record locked")?;
        let path = std::path::Path::new(JOURNAL_PATH);
        if let Some(mut j) = os_journal::read(path)? {
            // An installed slot is never downloaded again automatically while
            // the reboot outcome remains unknown.
            if !matches!(j.stage, Stage::Installing | Stage::PendingReboot) {
                j.stage = Stage::Failed;
            }
            j.error = Some(error.chars().take(4000).collect());
            os_journal::write(path, &j)?;
        }
        let _ = report_applied(server, key, &info.version, Some(error));
    }
    result
}

fn apply_inner(
    server: &str,
    key: Option<&str>,
    info: &UpdateInfo,
    on_progress: impl Fn(&str, u8),
) -> Result<(), String> {
    ensure_upgrade(info, &current_os_version())?;
    info!(
        "os-update: applying {} ({} bytes, release {})",
        info.version, info.size_bytes, info.release_id
    );

    // 1. Download with chunked streaming + resume support.
    // Streams directly to disk (no 1.2GB in RAM). On network failure,
    // resumes from where it left off using Range header. Retries up to
    // 5 times with 10s backoff between attempts.
    let url = format!("{}{}", server, info.download_url);
    on_progress("Preparing", 0);
    let staging_dir = PathBuf::from("/var/lib/betterframe/tmp");
    fs::create_dir_all(&staging_dir).map_err(|e| format!("mkdir staging: {e}"))?;
    let bundle_path = staging_dir.join(format!("os-{}.raucb", info.release_id));

    let max_retries = 5;
    for attempt in 1..=max_retries {
        let existing_bytes = fs::metadata(&bundle_path).map(|m| m.len()).unwrap_or(0);

        // If we already have the full file from a previous attempt, skip download.
        if existing_bytes >= info.size_bytes {
            break;
        }

        info!(
            "os-update: download attempt {attempt}/{max_retries} (resuming from {existing_bytes} / {} bytes)",
            info.size_bytes
        );

        let client = crate::network::blocking_client();
        let mut req = client.get(&url);
        if let Some(key) = key {
            req = req.header("Authorization", format!("Bearer {key}"));
        }
        if existing_bytes > 0 {
            req = req.header("Range", format!("bytes={existing_bytes}-"));
        }

        let resp = match req.timeout(Duration::from_secs(300)).send() {
            Ok(r) => r,
            Err(e) => {
                warn!("os-update: download request failed (attempt {attempt}): {e}");
                if attempt < max_retries {
                    std::thread::sleep(Duration::from_secs(10));
                    continue;
                }
                return Err(format!("download failed after {max_retries} attempts: {e}"));
            }
        };

        let status = resp.status().as_u16();

        if status != 200 && status != 206 {
            return Err(format!("download HTTP {status}"));
        }
        let resumed = existing_bytes > 0 && status == 206;
        if existing_bytes > 0 && !resumed {
            warn!("os-update: server ignored Range; restarting download");
        }

        // Stream chunks to disk.
        use std::io::Write;
        let mut file = fs::OpenOptions::new()
            .create(true)
            .write(true)
            .append(resumed)
            .truncate(!resumed)
            .open(&bundle_path)
            .map_err(|e| format!("open bundle file: {e}"))?;

        let mut reader = resp;
        let mut buf = vec![0u8; 256 * 1024]; // 256KB chunks
        let mut downloaded = if resumed { existing_bytes } else { 0 };
        let mut stream_ok = true;

        loop {
            if cancel_requested() {
                let _ = fs::remove_file(&bundle_path);
                return Err("os update canceled after channel change".to_string());
            }
            match std::io::Read::read(&mut reader, &mut buf) {
                Ok(0) => break, // EOF
                Ok(n) => {
                    file.write_all(&buf[..n])
                        .map_err(|e| format!("write chunk: {e}"))?;
                    downloaded += n as u64;
                    let pct = ((downloaded as f64 / info.size_bytes as f64) * 90.0) as u8;
                    on_progress("Downloading", pct);
                    if downloaded % (50 * 1024 * 1024) < (256 * 1024) as u64 {
                        info!(
                            "os-update: {downloaded} / {} bytes ({pct}%)",
                            info.size_bytes
                        );
                    }
                }
                Err(e) => {
                    warn!("os-update: stream error at {downloaded} bytes (attempt {attempt}): {e}");
                    stream_ok = false;
                    break;
                }
            }
        }
        file.sync_all().ok();

        if stream_ok && downloaded >= info.size_bytes {
            break; // Download complete
        }

        if attempt < max_retries {
            info!("os-update: retrying in 10s...");
            std::thread::sleep(Duration::from_secs(10));
        } else {
            return Err(format!(
                "download incomplete after {max_retries} attempts ({downloaded}/{} bytes)",
                info.size_bytes
            ));
        }
    }

    on_progress("Verifying", 90);
    // 2. sha256 verify the complete file on disk.
    let file_size = fs::metadata(&bundle_path).map(|m| m.len()).unwrap_or(0);
    if file_size != info.size_bytes {
        let _ = fs::remove_file(&bundle_path);
        return Err(format!(
            "size mismatch: expected {}, got {file_size}",
            info.size_bytes
        ));
    }

    let mut hasher = Sha256::new();
    let mut f = fs::File::open(&bundle_path).map_err(|e| format!("open for hash: {e}"))?;
    let mut buf = vec![0u8; 256 * 1024];
    loop {
        match std::io::Read::read(&mut f, &mut buf) {
            Ok(0) => break,
            Ok(n) => hasher.update(&buf[..n]),
            Err(e) => {
                let _ = fs::remove_file(&bundle_path);
                return Err(format!("read for hash: {e}"));
            }
        }
    }
    drop(f);
    let digest = hasher.finalize();
    let got_sha = hex_lower(&digest);
    if got_sha != info.sha256 {
        let _ = fs::remove_file(&bundle_path);
        return Err(format!(
            "sha256 mismatch: expected {}, got {got_sha}",
            info.sha256
        ));
    }

    on_progress("Installing", 95);
    if cancel_requested() {
        let _ = fs::remove_file(&bundle_path);
        return Err("os update canceled after channel change".to_string());
    }
    // Recheck after the potentially long download before touching the host OS.
    if !enabled() {
        return Err("OS updates are disabled or this is not a full BetterFrame OS installation".into());
    }
    // 4. Ensure rauc daemon is running. `rauc install` talks to the D-Bus
    // daemon; if it's not active the CLI exits with code 2.
    if let Ok(status) = Command::new("systemctl")
        .args(["is-active", "--quiet", "rauc.service"])
        .status()
    {
        if !status.success() {
            info!("os-update: rauc.service not active, attempting start");
            let start = Command::new("systemctl")
                .args(["start", "rauc.service"])
                .output();
            match start {
                Ok(out) if out.status.success() => {
                    info!("os-update: rauc.service started");
                }
                Ok(out) => {
                    let stderr = String::from_utf8_lossy(&out.stderr);
                    let msg = format!("rauc.service failed to start: {stderr}");
                    warn!("os-update: {msg}");
                    let _ = report_applied(server, key, &info.version, Some(&msg));
                    let _ = fs::remove_file(&bundle_path);
                    return Err(msg);
                }
                Err(e) => {
                    let msg = format!("systemctl start rauc.service: {e}");
                    warn!("os-update: {msg}");
                    let _ = report_applied(server, key, &info.version, Some(&msg));
                    let _ = fs::remove_file(&bundle_path);
                    return Err(msg);
                }
            }
        }
    }

    // Hand off to rauc. `rauc install` blocks until the bundle is fully
    // copied into the inactive slot and bootloader is flipped. Exit code 0
    // = success; anything else = leave current slot booted, no reboot.
    if !installer_idle() {
        return Err("OS installer is busy or unavailable; installation deferred".into());
    }
    save_stage(Stage::Installing, None)?;
    let mut command = Command::new("rauc");
    command
        .args(["install", bundle_path.to_str().unwrap_or("")])
        .stdout(Stdio::piped())
        .stderr(Stdio::piped());
    let mut child = spawn_installer(&mut command, save_stage)?;
    let mut child_stdout = child
        .stdout
        .take()
        .ok_or_else(|| "rauc stdout missing".to_string())?;
    let mut child_stderr = child
        .stderr
        .take()
        .ok_or_else(|| "rauc stderr missing".to_string())?;
    let stdout_reader = std::thread::spawn(move || {
        let mut bytes = Vec::new();
        let _ = child_stdout.read_to_end(&mut bytes);
        bytes
    });
    let stderr_reader = std::thread::spawn(move || {
        let mut bytes = Vec::new();
        let _ = child_stderr.read_to_end(&mut bytes);
        bytes
    });
    // Once RAUC has accepted the install, cancelling its CLI cannot cancel
    // the root daemon. Finish observing the transaction before retry/reboot.
    let status = loop {
        match child.try_wait() {
            Ok(Some(status)) => break status,
            Ok(None) => std::thread::sleep(Duration::from_secs(1)),
            Err(e) => {
                return Err(format!("RAUC outcome unknown; bundle retained: {e}"));
            }
        }
    };
    let stdout = stdout_reader.join().unwrap_or_default();
    let stderr = stderr_reader.join().unwrap_or_default();
    if !status.success() {
        let msg = format_command_failure("rauc install", status, &stdout, &stderr);
        warn!("os-update: {msg}");
        let _ = report_applied(server, key, &info.version, Some(&msg));
        // The CLI may have lost D-Bus while the daemon continues. Keep the
        // bundle and blocked Installing record until an explicit retry.
        return Err(msg);
    }
    let _ = fs::remove_file(&bundle_path);

    // 5. Report success BEFORE reboot. After this we lose the server
    // connection mid-call; that's fine, server sets last_attempt_at from
    // the next heartbeat anyway, but recording success now means the
    // admin UI shows progress immediately.
    let _ = report_applied(server, key, &info.version, None);
    save_stage(Stage::PendingReboot, None)?;

    on_progress("Rebooting", 100);
    info!("os-update: rauc install OK → rebooting into the new slot");
    // The root-run RAUC hook schedules the reboot after it finishes patching
    // the target slot. The kiosk service has NoNewPrivileges=yes for WebKit,
    // so attempting sudo here can never work.
    std::thread::sleep(Duration::from_secs(180));
    let detail = fs::read_to_string("/run/betterframe-rauc/os-reboot-status.txt")
        .unwrap_or_else(|_| "No reboot-service diagnostics available from this OS".into());
    let message = format!(
        "OS installed but reboot was not confirmed: {}. Retry from BetterFrame.",
        detail.trim()
    );
    let _ = report_applied(server, key, &info.version, Some(&message));
    Err(message)
}

fn newer_update(check: CheckResponse, current_version: &str) -> Option<UpdateInfo> {
    if check.up_to_date {
        return None;
    }
    let update = check.update.filter(|update| {
        crate::core::version::is_version_upgrade(&update.version, current_version)
    });
    if update.is_none() {
        warn!("os-update: refusing non-upgrade offered for installed version {current_version}");
    }
    update
}

fn ensure_upgrade(info: &UpdateInfo, current_version: &str) -> Result<(), String> {
    if crate::core::version::is_version_upgrade(&info.version, current_version) {
        Ok(())
    } else {
        Err(format!(
            "refusing OS downgrade or reinstall: installed {current_version}, offered {}",
            info.version
        ))
    }
}

fn report_applied(
    server: &str,
    key: Option<&str>,
    version: &str,
    error: Option<&str>,
) -> Result<(), String> {
    let Some(key) = key else {
        return Ok(());
    };
    let payload = if let Some(err) = error {
        serde_json::json!({ "version": version, "state": "failed", "error": err })
    } else {
        serde_json::json!({ "version": version, "state": "pending_reboot" })
    };
    crate::network::blocking_client()
        .post(format!("{server}/api/kiosk/os/status"))
        .header("Authorization", format!("Bearer {key}"))
        .json(&payload)
        .timeout(Duration::from_secs(5))
        .send()
        .and_then(|response| response.error_for_status())
        .map(|_| ())
        .map_err(|e| format!("report applied: {e}"))
}

pub fn report_confirmed(server: &str, key: &str) -> bool {
    let Ok(_lock) = JOURNAL_LOCK.lock() else {
        return false;
    };
    let path = std::path::Path::new(JOURNAL_PATH);
    let running = current_os_version();
    let id = boot_id();
    if running.is_empty() || id.is_empty() {
        return false;
    }
    let mut journal = match os_journal::read(path) {
        Ok(j) => j,
        Err(_) => return false,
    };
    let mut version = running.clone();
    let mut state = "confirmed";
    let mut error = None;
    if let Some(j) = journal.as_mut() {
        j.reconcile(&id, &running, boot_is_confirmed());
        version = j.version.clone();
        match j.stage {
            Stage::Downloading | Stage::Installing => return false,
            Stage::PendingReboot if j.boot_id == id => return false,
            Stage::RolledBack => {
                state = "rolled_back";
                error = j.error.clone();
            }
            Stage::Failed => {
                state = "failed";
                error = j.error.clone();
            }
            _ => {
                if !boot_is_confirmed() {
                    return false;
                }
                j.stage = Stage::Confirmed;
                j.error = None;
            }
        }
        if os_journal::write(path, j).is_err() {
            return false;
        }
    } else if !boot_is_confirmed() {
        return false;
    }
    let ok = crate::network::blocking_client()
        .post(format!("{server}/api/kiosk/os/status"))
        .header("Authorization", format!("Bearer {key}"))
        .json(&serde_json::json!({ "version": version, "state": state, "error": error }))
        .timeout(Duration::from_secs(5))
        .send()
        .map(|r| r.status().is_success())
        .unwrap_or(false);
    if ok && state == "confirmed" {
        crate::update_guard::record_success("os", &version);
    }
    ok
}

pub fn boot_is_confirmed() -> bool {
    std::path::Path::new("/run/betterframe/rauc-confirmed").exists()
        || !std::path::Path::new("/etc/rauc/system.conf").exists()
}

// Persist Installing before spawn to cover power loss during handoff, but
// undo that uncertainty when the OS proves no child process was created.
fn spawn_installer(
    command: &mut Command,
    persist: impl FnOnce(Stage, Option<String>) -> Result<(), String>,
) -> Result<std::process::Child, String> {
    command.spawn().map_err(|error| {
        let message = format!("rauc spawn: {error}");
        match persist(Stage::Failed, Some(message.clone())) {
            Ok(()) => message,
            Err(persist_error) => {
                format!("{message}; could not persist retryable state: {persist_error}")
            }
        }
    })
}

#[cfg(test)]
mod spawn_tests {
    use super::*;

    #[test]
    fn missing_executable_restores_retryable_journal() {
        let directory = std::env::temp_dir().join(format!("bf-os-spawn-{}", std::process::id()));
        fs::create_dir_all(&directory).unwrap();
        let path = directory.join("journal.json");
        let mut journal = Journal {
            version: "1.0.1".into(),
            release_id: "release".into(),
            boot_id: "boot".into(),
            stage: Stage::Installing,
            error: None,
        };
        os_journal::write(&path, &journal).unwrap();
        let error = spawn_installer(
            &mut Command::new(directory.join("missing-rauc")),
            |stage, error| {
                journal.stage = stage;
                journal.error = error;
                os_journal::write(&path, &journal)
            },
        )
        .unwrap_err();
        let persisted = os_journal::read(&path).unwrap().unwrap();
        assert_eq!(persisted.stage, Stage::Failed);
        assert!(!persisted.blocks_apply());
        assert_eq!(persisted.error.as_deref(), Some(error.as_str()));
        fs::remove_dir_all(directory).unwrap();
    }
}

fn format_command_failure(
    command: &str,
    status: std::process::ExitStatus,
    stdout: &[u8],
    stderr: &[u8],
) -> String {
    let code = status
        .code()
        .map(|c| c.to_string())
        .unwrap_or_else(|| "unknown".to_string());
    let mut msg = format!("{command} failed (exit code {code}, status {status:?})");
    append_command_output(&mut msg, "stdout", stdout);
    append_command_output(&mut msg, "stderr", stderr);
    msg
}

fn append_command_output(msg: &mut String, label: &str, bytes: &[u8]) {
    let text = String::from_utf8_lossy(bytes);
    let trimmed = text.trim();
    if trimmed.is_empty() {
        return;
    }

    const MAX_OUTPUT_CHARS: usize = 4000;
    msg.push_str("; ");
    msg.push_str(label);
    msg.push_str(": ");
    if trimmed.chars().count() <= MAX_OUTPUT_CHARS {
        msg.push_str(trimmed);
        return;
    }

    let start = trimmed
        .char_indices()
        .nth(trimmed.chars().count().saturating_sub(MAX_OUTPUT_CHARS))
        .map(|(idx, _)| idx)
        .unwrap_or(0);
    msg.push_str("[truncated] ");
    msg.push_str(&trimmed[start..]);
}

fn hex_lower(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push(HEX[(b >> 4) as usize] as char);
        s.push(HEX[(b & 0x0f) as usize] as char);
    }
    s
}
