#!/bin/bash
# Runs inside the pi-gen chroot. Installs the BetterFrame kiosk binary +
# systemd unit + cage PAM + plymouth theme. Mirrors setup-pi-kiosk.sh but
# baked into the image so first boot is fully provisioned.
set -euo pipefail

# --- bfadmin user (replaces pi-gen's username/password config) ---
# Pi-gen's built-in user setup reinstalls the firstboot wizard AFTER
# custom stages run. We create the admin user ourselves to avoid that.
if ! id -u bfadmin >/dev/null 2>&1; then
  useradd -m -s /usr/sbin/nologin bfadmin
fi

# --- bfkiosk user ---
if ! id -u bfkiosk >/dev/null 2>&1; then
  useradd -m -s /usr/sbin/nologin bfkiosk
fi
for grp in video render input audio systemd-journal; do
  if getent group "$grp" >/dev/null; then
    usermod -a -G "$grp" bfkiosk
  fi
done

# --- Deps for first-boot partition expansion ---
apt-get -y install cloud-guest-utils e2fsprogs 2>/dev/null || true

# --- Tailscale VPN ---
curl -fsSL https://tailscale.com/install.sh | sh
command -v tailscale >/dev/null
systemctl enable tailscaled
systemctl disable tailscaled.service 2>/dev/null || true
# Tailscale auth is triggered from the admin UI, not on boot.
# tailscaled runs but doesn't auto-connect until auth key is provided.

# --- Binary ---
install -d -o bfkiosk -g bfkiosk -m 755 /opt/betterframe/kiosk
install -m 755 /tmp/bf-files/betterframe-kiosk /opt/betterframe/kiosk/betterframe-kiosk
# State dir for firmware marker file (rollback script reads this)
install -d -o bfkiosk -g bfkiosk -m 755 /var/lib/betterframe/kiosk

# --- Systemd unit + PAM + rollback hook ---
install -m 644 /tmp/bf-files/betterframe-kiosk.service /etc/systemd/system/betterframe-kiosk.service
install -m 644 /tmp/bf-files/cage.pam                  /etc/pam.d/cage
install -m 755 /tmp/bf-files/betterframe-firmware-rollback.sh \
  /usr/local/sbin/betterframe-firmware-rollback.sh
install -m 644 /tmp/bf-files/betterframe-rauc-mark-good.service \
  /etc/systemd/system/betterframe-rauc-mark-good.service
install -m 755 /tmp/bf-files/betterframe-rauc-mark-good.sh \
  /usr/local/sbin/betterframe-rauc-mark-good.sh
install -m 644 /tmp/bf-files/betterframe-expand-data.service \
  /etc/systemd/system/betterframe-expand-data.service
install -m 755 /tmp/bf-files/betterframe-expand-data.sh \
  /usr/local/sbin/betterframe-expand-data.sh
install -m 755 /tmp/bf-files/betterframe-apply-managed-config.sh \
  /usr/local/sbin/betterframe-apply-managed-config.sh
install -m 755 /tmp/bf-files/randomize-image-users.sh \
  /usr/local/sbin/randomize-image-users.sh
install -d -m 755 /etc/sudoers.d
cat > /etc/sudoers.d/betterframe-managed-config <<'SUDOERS'
bfkiosk ALL=(root) NOPASSWD: /usr/local/sbin/betterframe-apply-managed-config.sh *
SUDOERS
chmod 440 /etc/sudoers.d/betterframe-managed-config
install -d -m 755 /etc/tmpfiles.d
install -m 644 /tmp/bf-files/betterframe-kiosk.conf /etc/tmpfiles.d/betterframe-kiosk.conf
install -d -m 755 /etc/udev/rules.d
install -m 644 /tmp/bf-files/90-betterframe-no-hid.rules /etc/udev/rules.d/90-betterframe-no-hid.rules

# --- RAUC OS-OTA config ---
# system.conf names the A/B slots + the custom bootloader backend.
# keyring.pem is the operator's CA cert (generated by
# scripts/gen-rauc-signing-keys.sh, committed at deploy/rauc/ca-cert.pem).
# Without keyring.pem, RAUC refuses every bundle.
install -d -m 755 /etc/rauc
install -m 644 /tmp/bf-files/rauc-system.conf /etc/rauc/system.conf
if [ -f /tmp/bf-files/rauc-keyring.pem ]; then
  install -m 644 /tmp/bf-files/rauc-keyring.pem /etc/rauc/keyring.pem
else
  echo "WARNING: no rauc-keyring.pem staged — OS OTA will refuse all bundles" >&2
fi
install -m 755 /tmp/bf-files/betterframe-rauc-boot.sh /usr/local/sbin/betterframe-rauc-boot.sh
# RAUC's Debian package ships without systemd unit + D-Bus activation files.
# Without these, `rauc install` and `rauc status` fail because the D-Bus
# daemon name de.pengutronix.rauc is never registered.
install -m 644 /tmp/bf-files/rauc.service /etc/systemd/system/rauc.service
install -d -m 755 /usr/share/dbus-1/system-services
install -m 644 /tmp/bf-files/de.pengutronix.rauc.service \
  /usr/share/dbus-1/system-services/de.pengutronix.rauc.service
install -d -m 755 /usr/share/dbus-1/system.d
install -m 644 /tmp/bf-files/de.pengutronix.rauc.conf \
  /usr/share/dbus-1/system.d/de.pengutronix.rauc.conf

# --- Firewall: default-drop inbound, LAN-only kiosk local API ---
# Replaces any default nftables config Debian ships.
install -m 644 /tmp/bf-files/nftables.conf /etc/nftables.conf
systemctl enable nftables.service

# Default env file — operator may edit on first boot to point at their server.
cat > /etc/default/betterframe-kiosk <<'EOF'
# Runtime env for betterframe-kiosk. Edit and `systemctl restart betterframe-kiosk`.
# Override the BF server discovery (default tries localhost → betterframe.local
# → frame-eu.betterportal.net):
# BETTERFRAME_SERVER=https://frame.example.com

# Enable kiosk-app OTA. This image is curated and signed by us — fresh dev
# builds auto-deploy once they land in the BF server (via the build workflow's
# auto-import step). Set to 0 to pin a kiosk to its current binary.
BF_ENABLE_APP_OTA=1

# Enable full-OS RAUC OTA. The image ships with A/B partitions + rauc
# preinstalled. Set to 0 to pin OS version manually (kiosk-app updates
# still flow via BF_ENABLE_APP_OTA).
BF_ENABLE_OS_OTA=1

# Enable ONVIF event subscriptions: kiosk subscribes to PullPoint on
# every ONVIF camera in its bundle, polls every 3s, forwards events
# (motion, ANPR, analytics, line crossing, etc.) to the BF server +
# Node-RED. Set to 0 if no ONVIF cameras on the network.
BF_ENABLE_ONVIF_EVENTS=1

# Firmware channel for this image. Controls terminal access (dev only)
# and which update channel the kiosk polls. Change to "stable" or "beta"
# for production deployments.
BF_FIRMWARE_CHANNEL=dev
EOF

# Plymouth boot splash
install -d -m 755 /usr/share/plymouth/themes/betterframe
install -m 644 /tmp/bf-files/betterframe.plymouth /usr/share/plymouth/themes/betterframe/betterframe.plymouth
install -m 644 /tmp/bf-files/betterframe.script   /usr/share/plymouth/themes/betterframe/betterframe.script
install -m 644 /tmp/bf-files/logo.png             /usr/share/plymouth/themes/betterframe/logo.png
plymouth-set-default-theme betterframe || true

# --- Invisible cursor theme ---
# cage/wlroots renders a stale cursor even when input devices are blocked.
# XCURSOR_SIZE=1 doesn't reliably hide it on Pi 5 GPU. A transparent
# cursor theme is the nuclear fix — every cursor shape is a 1x1 transparent
# pixel so there's literally nothing to render.
CURSOR_DIR=/usr/share/icons/betterframe-empty/cursors
install -d -m 755 "$CURSOR_DIR"
# XCursor/wlroots looks for index.theme (not cursor.theme) when resolving
# XCURSOR_THEME. Install as both so update-alternatives and XCursor agree.
install -m 644 /tmp/bf-files/cursor.theme /usr/share/icons/betterframe-empty/index.theme
install -m 644 /tmp/bf-files/cursor.theme /usr/share/icons/betterframe-empty/cursor.theme
# Generate valid 1x1 transparent Xcursor files. Previous generator had a
# missing version field → malformed → wlroots fell back to default cursor.
# Xcursor format: file header (16) + TOC entry (12) + image chunk (36+4=40) = 68 bytes.
python3 -c "
import struct, os
# File header: magic + header_size + version(1.0) + ntoc
hdr = b'Xcur' + struct.pack('<III', 16, 0x00010000, 1)
# TOC: type(image=0xfffd0002) + subtype(nominal=1) + position(28)
toc = struct.pack('<III', 0xfffd0002, 1, 28)
# Image chunk header (36 bytes): header_size + type + nominal + version + w + h + xhot + yhot + delay
img = struct.pack('<IIIIIIIII', 36, 0xfffd0002, 1, 1, 1, 1, 0, 0, 0)
# 1 ARGB pixel, fully transparent
px = struct.pack('<I', 0)
data = hdr + toc + img + px
for name in ['default','left_ptr','arrow','watch','hand2','text','xterm',
    'top_left_corner','top_right_corner','bottom_left_corner',
    'bottom_right_corner','sb_h_double_arrow','sb_v_double_arrow',
    'fleur','crosshair','question_arrow','x_cursor','pirate',
    'sb_left_arrow','sb_right_arrow','sb_up_arrow','sb_down_arrow',
    'top_side','bottom_side','left_side','right_side']:
  with open(os.path.join('$CURSOR_DIR', name), 'wb') as f:
    f.write(data)
"
# Set as system default cursor theme
update-alternatives --install /usr/share/icons/default/index.theme x-cursor-theme \
  /usr/share/icons/betterframe-empty/cursor.theme 100 2>/dev/null || true
# Per-user cursor config for bfkiosk (cage reads user's icon theme)
install -d -o bfkiosk -g bfkiosk -m 755 /home/bfkiosk/.icons/default
cat > /home/bfkiosk/.icons/default/index.theme <<'CURSOR'
[Icon Theme]
Inherits=betterframe-empty
CURSOR
chown bfkiosk:bfkiosk /home/bfkiosk/.icons/default/index.theme

# --- NTP — critical for WSSE auth (camera checks timestamp) ---
mkdir -p /etc/systemd/timesyncd.conf.d
cat > /etc/systemd/timesyncd.conf.d/betterframe.conf <<'NTP'
[Time]
NTP=0.pool.ntp.org 1.pool.ntp.org 2.pool.ntp.org 3.pool.ntp.org
FallbackNTP=time.google.com time.cloudflare.com
NTP
systemctl enable systemd-timesyncd 2>/dev/null || true

# --- Enable services, disable noise ---
systemctl enable seatd
systemctl enable betterframe-kiosk.service
systemctl enable betterframe-rauc-mark-good.service
systemctl enable betterframe-expand-data.service
systemctl enable rauc.service 2>/dev/null || true
/usr/local/sbin/randomize-image-users.sh bfadmin bfkiosk

# Boot to multi-user, no display manager, no welcome wizard, no getty on tty1.
systemctl set-default multi-user.target
for dm in lightdm gdm gdm3 sddm; do
  systemctl disable "${dm}.service" 2>/dev/null || true
  systemctl mask    "${dm}.service" 2>/dev/null || true
done
# Mask ALL gettys — not just tty1. Ctrl+Alt+Fx shouldn't reach a login.
for tty in 1 2 3 4 5 6; do
  systemctl disable "getty@tty${tty}.service" 2>/dev/null || true
  systemctl mask    "getty@tty${tty}.service" 2>/dev/null || true
done
# Also mask the serial console + autovt template so logind can't spawn new ones.
systemctl mask serial-getty@.service getty@.service 2>/dev/null || true
systemctl mask ctrl-alt-del.target 2>/dev/null || true
# Disable VT switching entirely via logind: no auto-VTs, no reserved VT.
mkdir -p /etc/systemd/logind.conf.d
cat > /etc/systemd/logind.conf.d/betterframe-lockdown.conf <<'LOGIND'
[Login]
NAutoVTs=0
ReserveVT=0
LOGIND
# Lock the physical console: block sulogin / emergency shell.
systemctl mask emergency.service rescue.service emergency.target rescue.target 2>/dev/null || true

systemctl disable ssh.service ssh.socket 2>/dev/null || true
systemctl mask ssh.service ssh.socket 2>/dev/null || true
systemctl disable bluetooth.service hciuart.service 2>/dev/null || true
systemctl mask bluetooth.service hciuart.service 2>/dev/null || true

# Kill EVERY first-run wizard / setup screen Pi OS ships. Purge the
# packages AND nuke any leftover desktop/autostart files so nothing
# survives to flash "configure your raspberry" on screen.
apt-get -y purge piwiz userconf-pi pi-greeter rpd-plym-splash \
  initial-setup initial-setup-gui rpi-first-boot-wizard 2>/dev/null || true
# Nuke ALL autostart entries related to setup/wizard/greeter.
rm -f /etc/xdg/autostart/piwiz.desktop
rm -f /etc/xdg/autostart/setup-wizard.desktop
rm -f /etc/xdg/autostart/initial-setup*.desktop
rm -f /etc/xdg/autostart/*wizard*.desktop
rm -f /etc/xdg/autostart/*setup*.desktop
rm -f /etc/xdg/autostart/*greeter*.desktop
rm -rf /usr/share/applications/piwiz.desktop
rm -rf /usr/share/applications/initial-setup*.desktop
# userconf-pi drops a first-boot service that prompts for user/pass.
systemctl disable userconfig.service 2>/dev/null || true
systemctl mask userconfig.service 2>/dev/null || true
systemctl disable rpi-first-boot-wizard.service 2>/dev/null || true
systemctl mask rpi-first-boot-wizard.service 2>/dev/null || true
# raspi-config has first-boot triggers via /etc/profile.d and init scripts.
rm -f /etc/profile.d/raspi-config.sh 2>/dev/null || true
rm -f /etc/init.d/resize2fs_once 2>/dev/null || true
systemctl disable raspi-config.service 2>/dev/null || true
systemctl mask raspi-config.service 2>/dev/null || true
# Mark first-boot as done so any surviving checks think setup completed.
mkdir -p /var/lib/userconf-pi
touch /var/lib/userconf-pi/userconf
# Prevent pi-gen firstrun.sh from triggering on boot.
if [ -f /boot/firmware/firstrun.sh ]; then rm -f /boot/firmware/firstrun.sh; fi
# Remove any login program on console.
rm -f /etc/systemd/system/getty.target.wants/* 2>/dev/null || true

# Suppress console motd / issue.
: > /etc/motd
printf 'BetterFrame Kiosk\n\n' > /etc/issue
rm -f /etc/update-motd.d/* 2>/dev/null || true

# Remove desktop packages that could show setup wizards. Be specific —
# wildcard 'lx*' kills libwlroots which removes cage (our compositor).
apt-get -y purge piwiz userconf-pi rpi-first-boot-wizard pi-greeter \
  rpd-plym-splash lightdm gdm3 sddm desktop-base \
  raspberrypi-ui-mods lxde lxde-core lxpanel lxsession lxterminal \
  labwc wayfire 2>/dev/null || true
# Mark cage as manually installed so autoremove won't touch it.
apt-mark manual cage 2>/dev/null || true
apt-get -y autoremove 2>/dev/null || true

# Force multi-user via kernel cmdline (overrides any default target)
# Boot config: quiet splash + no rainbow.
if [ -f /boot/firmware/cmdline.txt ]; then BOOT_DIR=/boot/firmware
else BOOT_DIR=/boot; fi
CMDLINE="${BOOT_DIR}/cmdline.txt"
CONFIG="${BOOT_DIR}/config.txt"
if [ -f "$CMDLINE" ]; then
  for flag in quiet splash plymouth.ignore-serial-consoles loglevel=0 vt.global_cursor_default=0 logo.nologo systemd.unit=multi-user.target; do
    if ! grep -qw -- "$flag" "$CMDLINE"; then
      sed -i "s|\$| $flag|" "$CMDLINE"
    fi
  done
fi
if [ -f "$CONFIG" ] && ! grep -q '^disable_splash=1' "$CONFIG"; then
  printf '\n# BetterFrame: disable firmware rainbow splash\ndisable_splash=1\n' >> "$CONFIG"
fi

rm -rf /tmp/bf-files
echo "BetterFrame kiosk stage complete."
