#!/bin/bash -e
# Runs inside the pi-gen chroot. Installs the BetterFrame kiosk binary +
# systemd unit + cage PAM + plymouth theme. Mirrors setup-pi-kiosk.sh but
# baked into the image so first boot is fully provisioned.

# --- bfkiosk user ---
if ! id -u bfkiosk >/dev/null 2>&1; then
  useradd -m -s /usr/sbin/nologin bfkiosk
fi
for grp in video render input audio; do
  if getent group "$grp" >/dev/null; then
    usermod -a -G "$grp" bfkiosk
  fi
done

# --- Passwordless sudo for bfkiosk (remote terminal runs as root) ---
echo 'bfkiosk ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/betterframe-kiosk
chmod 440 /etc/sudoers.d/betterframe-kiosk

# --- Binary ---
install -d -o bfkiosk -g bfkiosk -m 755 /opt/betterframe/kiosk
install -m 755 /tmp/bf-files/betterframe-kiosk /opt/betterframe/kiosk/betterframe-kiosk
# State dir for firmware marker file (rollback script reads this)
install -d -o bfkiosk -g bfkiosk -m 755 /var/lib/betterframe/kiosk

# --- Systemd unit + PAM + rollback hook ---
install -m 644 /tmp/bf-files/betterframe-kiosk.service /etc/systemd/system/betterframe-kiosk.service
install -m 644 /tmp/bf-files/cage.pam                  /etc/pam.d/cage
install -m 755 /tmp/bf-files/betterframe-firmware-rollback.sh \
  /usr/local/sbin/betterframe-firmware-rollback.sh
install -m 644 /tmp/bf-files/betterframe-rauc-mark-good.service \
  /etc/systemd/system/betterframe-rauc-mark-good.service
install -m 755 /tmp/bf-files/betterframe-rauc-mark-good.sh \
  /usr/local/sbin/betterframe-rauc-mark-good.sh
install -d -m 755 /etc/tmpfiles.d
install -m 644 /tmp/bf-files/betterframe-kiosk.conf /etc/tmpfiles.d/betterframe-kiosk.conf
install -d -m 755 /etc/udev/rules.d
install -m 644 /tmp/bf-files/90-betterframe-no-hid.rules /etc/udev/rules.d/90-betterframe-no-hid.rules

# --- RAUC OS-OTA config ---
# system.conf names the A/B slots + the custom bootloader backend.
# keyring.pem is the operator's CA cert (generated by
# scripts/gen-rauc-signing-keys.sh, committed at deploy/rauc/ca-cert.pem).
# Without keyring.pem, RAUC refuses every bundle.
install -d -m 755 /etc/rauc
install -m 644 /tmp/bf-files/rauc-system.conf /etc/rauc/system.conf
if [ -f /tmp/bf-files/rauc-keyring.pem ]; then
  install -m 644 /tmp/bf-files/rauc-keyring.pem /etc/rauc/keyring.pem
else
  echo "WARNING: no rauc-keyring.pem staged — OS OTA will refuse all bundles" >&2
fi
install -m 755 /tmp/bf-files/betterframe-rauc-boot.sh /usr/local/sbin/betterframe-rauc-boot.sh

# --- Firewall: default-drop inbound, LAN-only kiosk local API ---
# Replaces any default nftables config Debian ships.
install -m 644 /tmp/bf-files/nftables.conf /etc/nftables.conf
systemctl enable nftables.service

# --- First-boot password rotation ---
# Replaces the image-default bfadmin password with a per-device random one
# the first time the kiosk boots. Stored at /etc/betterframe/admin-password
# (0400 root) AND printed to tty1 banner once. See script for details.
install -m 644 /tmp/bf-files/betterframe-firstboot.service \
  /etc/systemd/system/betterframe-firstboot.service
install -m 755 /tmp/bf-files/betterframe-firstboot.sh \
  /usr/local/sbin/betterframe-firstboot.sh
systemctl enable betterframe-firstboot.service

# Default env file — operator may edit on first boot to point at their server.
cat > /etc/default/betterframe-kiosk <<'EOF'
# Runtime env for betterframe-kiosk. Edit and `systemctl restart betterframe-kiosk`.
# Override the BF server discovery (default tries localhost → betterframe.local
# → frame-eu.betterportal.net):
# BETTERFRAME_SERVER=https://frame.example.com

# Enable kiosk-app OTA. This image is curated and signed by us — fresh dev
# builds auto-deploy once they land in the BF server (via the build workflow's
# auto-import step). Set to 0 to pin a kiosk to its current binary.
BF_ENABLE_APP_OTA=1

# Enable full-OS RAUC OTA. The image ships with A/B partitions + rauc
# preinstalled. Set to 0 to pin OS version manually (kiosk-app updates
# still flow via BF_ENABLE_APP_OTA).
BF_ENABLE_OS_OTA=1

# Enable ONVIF event subscriptions: kiosk subscribes to PullPoint on
# every ONVIF camera in its bundle, polls every 3s, forwards events
# (motion, ANPR, analytics, line crossing, etc.) to the BF server +
# Node-RED. Set to 0 if no ONVIF cameras on the network.
BF_ENABLE_ONVIF_EVENTS=1

# Firmware channel for this image. Controls terminal access (dev only)
# and which update channel the kiosk polls. Change to "stable" or "beta"
# for production deployments.
BF_FIRMWARE_CHANNEL=dev
EOF

# Plymouth boot splash
install -d -m 755 /usr/share/plymouth/themes/betterframe
install -m 644 /tmp/bf-files/betterframe.plymouth /usr/share/plymouth/themes/betterframe/betterframe.plymouth
install -m 644 /tmp/bf-files/betterframe.script   /usr/share/plymouth/themes/betterframe/betterframe.script
install -m 644 /tmp/bf-files/logo.png             /usr/share/plymouth/themes/betterframe/logo.png
plymouth-set-default-theme betterframe || true

# --- Invisible cursor theme ---
# cage/wlroots renders a stale cursor even when input devices are blocked.
# XCURSOR_SIZE=1 doesn't reliably hide it on Pi 5 GPU. A transparent
# cursor theme is the nuclear fix — every cursor shape is a 1x1 transparent
# pixel so there's literally nothing to render.
CURSOR_DIR=/usr/share/icons/betterframe-empty/cursors
install -d -m 755 "$CURSOR_DIR"
install -m 644 /tmp/bf-files/cursor.theme /usr/share/icons/betterframe-empty/cursor.theme
# Generate a 1x1 transparent X cursor for every standard cursor name.
# xcursorgen reads a config file and produces the binary Xcursor format.
# If xcursorgen is available (from x11-apps), use it; otherwise create
# a minimal raw Xcursor binary (header + 1px transparent image).
printf '1 0 0 /tmp/bf-transparent.png\n' > /tmp/bf-cursor.cfg
convert -size 1x1 xc:transparent /tmp/bf-transparent.png 2>/dev/null \
  || python3 -c "
import struct,sys
# Minimal 1x1 RGBA PNG
sys.stdout.buffer.write(b'\\x89PNG\\r\\n\\x1a\\n' + bytes([
  0,0,0,13,73,72,68,82,0,0,0,1,0,0,0,1,8,6,0,0,0,31,21,196,137,
  0,0,0,10,73,68,65,84,120,156,98,0,0,0,2,0,1,226,33,188,51,
  0,0,0,0,73,69,78,68,174,66,96,130]))
" > /tmp/bf-transparent.png
if command -v xcursorgen >/dev/null 2>&1; then
  for name in default left_ptr arrow watch hand2 text xterm top_left_corner \
    top_right_corner bottom_left_corner bottom_right_corner sb_h_double_arrow \
    sb_v_double_arrow fleur crosshair question_arrow; do
    xcursorgen /tmp/bf-cursor.cfg "$CURSOR_DIR/$name" 2>/dev/null || true
  done
else
  # Minimal Xcursor binary: magic + header + 1x1 ARGB image (4 bytes, all 0)
  python3 -c "
import struct, sys, os
magic = b'Xcur'
header = struct.pack('<III', 16, 1, 1)  # header_size, version, ntoc
toc = struct.pack('<III', 0xfffd0002, 36, 28)  # type=image, subtype=1, position
chunk_header = struct.pack('<IIIII', 36, 0xfffd0002, 1, 1, 1)  # size,type,subtype(nominal),width,height
xhot_yhot = struct.pack('<II', 0, 0)
delay = struct.pack('<I', 0)
pixel = struct.pack('<I', 0)  # 1 ARGB pixel, fully transparent
data = magic + header + toc + chunk_header + xhot_yhot + delay + pixel
for name in ['default','left_ptr','arrow','watch','hand2','text','xterm',
    'top_left_corner','top_right_corner','bottom_left_corner',
    'bottom_right_corner','sb_h_double_arrow','sb_v_double_arrow',
    'fleur','crosshair','question_arrow']:
  path = os.path.join('$CURSOR_DIR', name)
  with open(path, 'wb') as f: f.write(data)
" 2>/dev/null || true
fi
rm -f /tmp/bf-cursor.cfg /tmp/bf-transparent.png
# Set as system default cursor theme
update-alternatives --install /usr/share/icons/default/index.theme x-cursor-theme \
  /usr/share/icons/betterframe-empty/cursor.theme 100 2>/dev/null || true

# --- Enable services, disable noise ---
systemctl enable seatd
systemctl enable betterframe-kiosk.service
systemctl enable betterframe-rauc-mark-good.service
systemctl enable rauc.service 2>/dev/null || true

# Boot to multi-user, no display manager, no welcome wizard, no getty on tty1.
systemctl set-default multi-user.target
for dm in lightdm gdm gdm3 sddm; do
  systemctl disable "${dm}.service" 2>/dev/null || true
  systemctl mask    "${dm}.service" 2>/dev/null || true
done
# Mask ALL gettys — not just tty1. Ctrl+Alt+Fx shouldn't reach a login.
for tty in 1 2 3 4 5 6; do
  systemctl disable "getty@tty${tty}.service" 2>/dev/null || true
  systemctl mask    "getty@tty${tty}.service" 2>/dev/null || true
done
# Also mask the serial console + autovt template so logind can't spawn new ones.
systemctl mask serial-getty@.service getty@.service 2>/dev/null || true
systemctl mask ctrl-alt-del.target 2>/dev/null || true
# Disable VT switching entirely via logind: no auto-VTs, no reserved VT.
mkdir -p /etc/systemd/logind.conf.d
cat > /etc/systemd/logind.conf.d/betterframe-lockdown.conf <<'LOGIND'
[Login]
NAutoVTs=0
ReserveVT=0
LOGIND
# Lock the physical console: block sulogin / emergency shell.
systemctl mask emergency.service rescue.service emergency.target rescue.target 2>/dev/null || true

systemctl disable ssh.service ssh.socket 2>/dev/null || true
systemctl mask ssh.service ssh.socket 2>/dev/null || true
systemctl disable bluetooth.service hciuart.service 2>/dev/null || true
systemctl mask bluetooth.service hciuart.service 2>/dev/null || true

# Kill EVERY first-run wizard / setup screen Pi OS ships. Purge the
# packages AND nuke any leftover desktop/autostart files so nothing
# survives to flash "configure your raspberry" on screen.
apt-get -y purge piwiz userconf-pi pi-greeter rpd-plym-splash \
  initial-setup initial-setup-gui 2>/dev/null || true
rm -f /etc/xdg/autostart/piwiz.desktop
rm -f /etc/xdg/autostart/setup-wizard.desktop
rm -f /etc/xdg/autostart/initial-setup*.desktop
rm -rf /usr/share/applications/piwiz.desktop
rm -rf /usr/share/applications/initial-setup*.desktop
# userconf-pi drops a first-boot service that prompts for user/pass.
systemctl disable userconfig.service 2>/dev/null || true
systemctl mask userconfig.service 2>/dev/null || true
# Pi OS Bookworm+ uses rpi-first-boot-wizard.
apt-get -y purge rpi-first-boot-wizard 2>/dev/null || true
systemctl disable rpi-first-boot-wizard.service 2>/dev/null || true
systemctl mask rpi-first-boot-wizard.service 2>/dev/null || true
# Remove any login program on console.
rm -f /etc/systemd/system/getty.target.wants/* 2>/dev/null || true

# Suppress console motd / issue.
: > /etc/motd
printf 'BetterFrame Kiosk\n\n' > /etc/issue
rm -f /etc/update-motd.d/* 2>/dev/null || true

# Boot config: quiet splash + no rainbow.
if [ -f /boot/firmware/cmdline.txt ]; then BOOT_DIR=/boot/firmware
else BOOT_DIR=/boot; fi
CMDLINE="${BOOT_DIR}/cmdline.txt"
CONFIG="${BOOT_DIR}/config.txt"
if [ -f "$CMDLINE" ]; then
  for flag in quiet splash plymouth.ignore-serial-consoles loglevel=0 vt.global_cursor_default=0 logo.nologo; do
    if ! grep -qw -- "$flag" "$CMDLINE"; then
      sed -i "s|\$| $flag|" "$CMDLINE"
    fi
  done
fi
if [ -f "$CONFIG" ] && ! grep -q '^disable_splash=1' "$CONFIG"; then
  printf '\n# BetterFrame: disable firmware rainbow splash\ndisable_splash=1\n' >> "$CONFIG"
fi

rm -rf /tmp/bf-files
echo "BetterFrame kiosk stage complete."
