const TOKEN_KEY="betterframe.operator.stationToken";
const FAV_KEY="betterframe.operator.favorites";
const RECENT_KEY="betterframe.operator.recent";
const WALL_KEY="betterframe.operator.wallTarget";
const state={bootstrap:null,camera:null,stream:"main",filter:"all",duration:60,pc:null,whepResource:null,hid:null,hidTimer:null};
const $=id=>document.getElementById(id);
const jsonStore={get:(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}},set:(key,value)=>localStorage.setItem(key,JSON.stringify(value))};
function token(){return localStorage.getItem(TOKEN_KEY)||""}
async function api(path,options={}){const headers=new Headers(options.headers||{});if(token())headers.set("Authorization",`Bearer ${token()}`);if(options.body&&!headers.has("content-type"))headers.set("content-type","application/json");const response=await fetch(path,{...options,headers});if(response.status===401)throw new Error("unauthorized");if(!response.ok){let text=await response.text();throw new Error(text||`Request failed (${response.status})`)}const type=response.headers.get("content-type")||"";return type.includes("json")?response.json():response}
async function boot(){try{state.bootstrap=await api("/operator/api/bootstrap");$("enroll").classList.add("hidden");$("console").classList.remove("hidden");render();reconnectGrantedHid()}catch(err){if(err.message==="unauthorized"){localStorage.removeItem(TOKEN_KEY);$("console").classList.add("hidden");$("enroll").classList.remove("hidden")}else{$("enroll-error").textContent=err.message;$("enroll").classList.remove("hidden")}}}
$("enroll-form").addEventListener("submit",async event=>{event.preventDefault();$("enroll-error").textContent="";try{const enrolled=await api("/operator/api/enroll",{method:"POST",body:JSON.stringify({code:$("enroll-code").value})});localStorage.setItem(TOKEN_KEY,enrolled.token);await boot()}catch(err){$("enroll-error").textContent=err.message}});
function visibleCameras(){const q=$("search").value.trim().toLowerCase();const favorites=jsonStore.get(FAV_KEY,[]);const recent=jsonStore.get(RECENT_KEY,[]);let cameras=[...(state.bootstrap?.cameras||[])];if(state.filter==="favorites")cameras=cameras.filter(camera=>favorites.includes(camera.id));if(state.filter==="recent")cameras.sort((a,b)=>recent.indexOf(a.id)-recent.indexOf(b.id)).filter(camera=>recent.includes(camera.id));if(q)cameras=cameras.filter(camera=>[camera.name,camera.camera_number,...camera.labels].filter(Boolean).join(" ").toLowerCase().includes(q));return cameras}
function render(){renderCameras();renderWalls();if(!state.camera&&state.bootstrap.cameras.length)selectCamera(state.bootstrap.cameras[0].id)}
function renderCameras(){const list=$("camera-list");const cameras=visibleCameras();if(!cameras.length){const empty=document.createElement("p");empty.className="muted empty-state";empty.textContent=state.bootstrap?.cameras.length?"No cameras match this filter.":"No cameras are assigned to this kiosk with an operate label.";list.replaceChildren(empty);return}list.replaceChildren(...cameras.map(camera=>{const button=document.createElement("button");button.className=`camera-row${state.camera?.id===camera.id?" selected":""}`;button.innerHTML=`<i class="status ${camera.status}"></i><span><span class="camera-title"></span><span class="camera-sub"></span></span><span>${jsonStore.get(FAV_KEY,[]).includes(camera.id)?"★":""}</span>`;button.querySelector(".camera-title").textContent=camera.camera_number?`${camera.camera_number} · ${camera.name}`:camera.name;button.querySelector(".camera-sub").textContent=camera.labels.join(" · ")||camera.status;button.onclick=()=>selectCamera(camera.id);return button}))}
function selectCamera(id){const camera=state.bootstrap.cameras.find(item=>item.id===id);if(!camera)return;state.camera=camera;const recent=jsonStore.get(RECENT_KEY,[]).filter(item=>item!==id);recent.unshift(id);jsonStore.set(RECENT_KEY,recent.slice(0,20));$("camera-name").textContent=camera.name;$("camera-meta").textContent=[camera.camera_number,...camera.labels,camera.status].filter(Boolean).join(" · ");const favorites=jsonStore.get(FAV_KEY,[]);$("favorite").textContent=favorites.includes(id)?"★":"☆";const streams=new Set(camera.streams.map(item=>item.role));document.querySelectorAll("[data-stream]").forEach(button=>{button.disabled=!streams.has(button.dataset.stream);button.classList.toggle("active",button.dataset.stream===state.stream)});const hasPtz=camera.capabilities.some(item=>item.toLowerCase()==="ptz");$("ptz-controls").classList.toggle("hidden",!hasPtz);$("controls-grid").style.gridTemplateColumns=hasPtz?"":"1fr";renderCameras();renderPresets();preview()}
async function preview(){await stopPreview();if(!state.camera)return;$("video-state").textContent="Connecting…";$("video-state").style.display="grid";try{const session=await api("/operator/api/media/session",{method:"POST",body:JSON.stringify({camera_id:state.camera.id,stream:state.stream})});const pc=new RTCPeerConnection();state.pc=pc;pc.addTransceiver("video",{direction:"recvonly"});pc.ontrack=event=>{$("video").srcObject=event.streams[0];$("video-state").style.display="none"};pc.onconnectionstatechange=()=>{if(["failed","disconnected"].includes(pc.connectionState)){$("video-state").textContent="Live view disconnected";$("video-state").style.display="grid"}};const offer=await pc.createOffer();await pc.setLocalDescription(offer);await waitForIce(pc);const response=await api(session.whep_url,{method:"POST",headers:{"content-type":"application/sdp"},body:pc.localDescription.sdp});state.whepResource=response.headers.get("location");await pc.setRemoteDescription({type:"answer",sdp:await response.text()})}catch(err){$("video-state").textContent=err.message.includes("codec")?"Unsupported browser codec — try Sub stream":err.message;$("video-state").style.display="grid"}}
function waitForIce(pc){if(pc.iceGatheringState==="complete")return Promise.resolve();return new Promise(resolve=>{const timeout=setTimeout(resolve,3000);pc.addEventListener("icegatheringstatechange",()=>{if(pc.iceGatheringState==="complete"){clearTimeout(timeout);resolve()}},{once:false})})}
async function stopPreview(){if(state.whepResource){try{await api(state.whepResource,{method:"DELETE"})}catch{}state.whepResource=null}state.pc?.close();state.pc=null;$("video").srcObject=null}
document.querySelectorAll("[data-stream]").forEach(button=>button.onclick=()=>{state.stream=button.dataset.stream;document.querySelectorAll("[data-stream]").forEach(item=>item.classList.toggle("active",item===button));preview()});
document.querySelectorAll("[data-filter]").forEach(button=>button.onclick=()=>{state.filter=button.dataset.filter;document.querySelectorAll("[data-filter]").forEach(item=>item.classList.toggle("active",item===button));renderCameras()});
$("search").addEventListener("input",renderCameras);$("favorite").onclick=()=>{if(!state.camera)return;let items=jsonStore.get(FAV_KEY,[]);items=items.includes(state.camera.id)?items.filter(id=>id!==state.camera.id):[...items,state.camera.id];jsonStore.set(FAV_KEY,items);renderCameras();$("favorite").textContent=items.includes(state.camera.id)?"★":"☆"};
function stepCamera(delta){const list=visibleCameras();const index=Math.max(0,list.findIndex(camera=>camera.id===state.camera?.id));if(list.length)selectCamera(list[(index+delta+list.length)%list.length].id)}$("previous").onclick=()=>stepCamera(-1);$("next").onclick=()=>stepCamera(1);
async function onvif(action,params={}){if(!state.camera)throw new Error("Select a camera");const profileToken=state.camera.streams.find(item=>item.role===state.stream)?.profile_token||state.camera.streams[0]?.profile_token;return api(`/operator/api/cameras/${encodeURIComponent(state.camera.id)}/onvif`,{method:"POST",body:JSON.stringify({action,params:{...params,profileToken}})})}
let ptzActive=false;async function ptzMove(pan,tilt,zoom){ptzActive=true;try{await onvif("ptz.continuous_move",{pan,tilt,zoom,timeoutMs:500})}catch{}}async function ptzStop(){if(!ptzActive)return;ptzActive=false;try{await onvif("ptz.stop",{panTilt:true,zoom:true})}catch{}}
document.querySelectorAll("[data-ptz]").forEach(button=>{const values=button.dataset.ptz.split(",").map(Number);button.addEventListener("pointerdown",()=>ptzMove(...values));button.addEventListener("pointerup",ptzStop);button.addEventListener("pointercancel",ptzStop);button.addEventListener("pointerleave",ptzStop)});document.querySelector("[data-ptz-stop]").onclick=ptzStop;window.addEventListener("blur",ptzStop);
async function renderPresets(){const select=$("preset");select.innerHTML='<option value="">Preset…</option>';if(!state.camera?.capabilities.some(item=>item.toLowerCase()==="ptz"))return;try{const result=await onvif("ptz.get_presets");for(const preset of result.result?.data?.presets||[]){const option=document.createElement("option");option.value=preset.token;option.textContent=preset.name||preset.token;select.append(option)}}catch{}}$("preset").onchange=()=>{$("preset").value&&onvif("ptz.goto_preset",{presetToken:$("preset").value})};
function renderWalls(){const selected=jsonStore.get(WALL_KEY,{});const display=state.bootstrap.displays.find(item=>item.id===selected.display_id)||state.bootstrap.displays[0];const container=$("wall-buttons");container.replaceChildren(...state.bootstrap.displays.map((item,index)=>{const button=document.createElement("button");button.textContent=item.name||`Wall ${index+1}`;button.classList.toggle("active",item.id===display?.id);button.onclick=()=>{jsonStore.set(WALL_KEY,{display_id:item.id,cell_id:null});renderWalls();focus(item.id,false,null)};return button}));const cell=$("wall-cell");cell.innerHTML='<option value="">First empty tile</option>';for(const item of display?.cells||[]){const option=document.createElement("option");option.value=item.id;option.textContent=item.camera_name?`${item.id} · ${item.camera_name}`:item.id;option.selected=selected.cell_id===item.id;cell.append(option)}cell.onchange=()=>jsonStore.set(WALL_KEY,{display_id:display?.id,cell_id:cell.value||null})}
document.querySelectorAll("[data-duration]").forEach(button=>button.onclick=()=>{state.duration=button.dataset.duration==="pin"?null:Number(button.dataset.duration);document.querySelectorAll("[data-duration]").forEach(item=>item.classList.toggle("active",item===button))});
async function focus(displayId,fullscreen,cellOverride){if(!state.camera)return;const cellId=cellOverride===undefined?($("wall-cell").value||null):cellOverride;jsonStore.set(WALL_KEY,{display_id:displayId,cell_id:cellId});try{const result=await api(`/operator/api/displays/${encodeURIComponent(displayId)}/focus`,{method:"POST",body:JSON.stringify({camera_id:state.camera.id,stream:state.stream,target:fullscreen?{kind:"fullscreen"}:{kind:"cell",cell_id:cellId},duration_seconds:state.duration,restore:"previous"})});$("wall-state").textContent=`Focused ${state.camera.name} on ${result.cell_id||"full display"}`}catch(err){$("wall-state").textContent=err.message}}
$("wall-send").onclick=()=>{const selected=jsonStore.get(WALL_KEY,{});const displayId=selected.display_id||state.bootstrap.displays[0]?.id;displayId&&focus(displayId,false)};$("wall-fullscreen").onclick=()=>{const selected=jsonStore.get(WALL_KEY,{});const displayId=selected.display_id||state.bootstrap.displays[0]?.id;displayId&&focus(displayId,true)};$("wall-restore").onclick=async()=>{const selected=jsonStore.get(WALL_KEY,{});const displayId=selected.display_id||state.bootstrap.displays[0]?.id;if(displayId)await api(`/operator/api/displays/${encodeURIComponent(displayId)}/overrides`,{method:"DELETE"});$("wall-state").textContent="Previous layout restored"};$("wall-clear").onclick=async()=>{const selected=jsonStore.get(WALL_KEY,{});const displayId=selected.display_id||state.bootstrap.displays[0]?.id;if(displayId)await api(`/operator/api/displays/${encodeURIComponent(displayId)}/clear`,{method:"POST",body:"{}"});$("wall-state").textContent="Display cleared; Restore layout to return"};
async function reconnectGrantedHid(){if(!navigator.hid)return;const devices=await navigator.hid.getDevices();if(devices[0])attachHid(devices[0])}$("connect-hid").onclick=async()=>{if(!navigator.hid){$("hid-state").textContent="WebHID is unavailable in this browser";return}try{const devices=await navigator.hid.requestDevice({filters:[]});if(devices[0])attachHid(devices[0])}catch(err){$("hid-state").textContent=err.message}};
async function attachHid(device){if(!device.opened)await device.open();state.hid=device;$("hid-state").textContent=device.productName||"HID joystick connected";device.addEventListener("inputreport",event=>{const data=new Uint8Array(event.data.buffer);if(data.length<3)return;const axis=value=>(value-128)/127;const pan=Math.abs(axis(data[0]))>.15?axis(data[0]):0;const tilt=Math.abs(axis(data[1]))>.15?-axis(data[1]):0;const zoom=Math.abs(axis(data[2]))>.15?axis(data[2]):0;if(pan||tilt||zoom)ptzMove(pan,tilt,zoom);else ptzStop();clearTimeout(state.hidTimer);state.hidTimer=setTimeout(ptzStop,250)})}
window.addEventListener("beforeunload",()=>{ptzStop();stopPreview()});boot();
